/datum/unit_test/custom_sprite_region_map/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human/consistent)
	var/list/zones = custom_sprite_present_regions(human)
	for(var/zone in list(BODY_ZONE_HEAD, BODY_ZONE_CHEST, BODY_ZONE_L_ARM, BODY_ZONE_R_ARM, BODY_ZONE_PRECISE_L_HAND, BODY_ZONE_PRECISE_R_HAND, BODY_ZONE_L_LEG, BODY_ZONE_R_LEG))
		TEST_ASSERT((zone in zones), "A whole human must have a [zone] region.")
	TEST_ASSERT(!(CUSTOM_MARKING_ZONE_TAUR in zones), "A body without a taur organ has no taur region.")
	TEST_ASSERT(zones.Find(BODY_ZONE_PRECISE_L_HAND) == zones.Find(BODY_ZONE_L_ARM) + 1, "Each hand must come straight after its arm.")
	var/list/map = custom_sprite_region_map(human, zones, 32)
	TEST_ASSERT(map == custom_sprite_region_map(human, zones, 32), "Unchanged geometry must reuse the cached map.")
	for(var/direction in GLOB.custom_style_directions)
		var/list/rows = map[direction]
		TEST_ASSERT(!(length(rows) != 32 || length(rows[1]) != 32), "Region maps must be 32 rows of 32 pixels.")
		var/list/masks = list()
		for(var/zone in zones)
			masks[zone] = custom_sprite_body_draw_mask(human, zone, 32)[direction]
		for(var/y in 1 to 32)
			for(var/x in 1 to 32)
				var/list/covering = list()
				for(var/zone in zones)
					if(copytext(masks[zone][y], x, x + 1) == "1")
						covering += zone
				var/owner = custom_sprite_region_owner(rows, zones, x - 1, y - 1)
				TEST_ASSERT(!(length(covering) && !(owner in covering)), "Pixel [x],[y] in view [direction] must belong to a region whose mask covers it.")
				TEST_ASSERT(!(!length(covering) && owner), "Pixel [x],[y] in view [direction] is outside every mask and must have no region.")
				if(length(covering) == 1)
					TEST_ASSERT(owner == covering[1], "A pixel only one region covers must belong to it.")
				// Arms and the torso share a layer, so whichever the body draws later owns their overlap.
				for(var/arm in list(BODY_ZONE_L_ARM, BODY_ZONE_R_ARM))
					var/hand = custom_marking_partner(arm)
					if((BODY_ZONE_CHEST in covering) && (arm in covering) && !(hand in covering))
						TEST_ASSERT(owner == (zones.Find(BODY_ZONE_CHEST) > zones.Find(arm) ? BODY_ZONE_CHEST : arm), "The torso/arm overlap at [x],[y] must follow draw order.")
		// A hand's own pixels sit on the high layer, over every ordinary limb on a plain human.
		// Its wrist band shares the arm's layer, so the torso may cover it in side views.
		for(var/hand in list(BODY_ZONE_PRECISE_L_HAND, BODY_ZONE_PRECISE_R_HAND))
			var/icon/palm = custom_sprite_silhouette(human.get_bodypart(GLOB.custom_marking_hand_arms[hand]), TRUE)
			for(var/y in 1 to 32)
				for(var/x in 1 to 32)
					if(palm.GetPixel(x, 33 - y, "", text2num(direction)))
						TEST_ASSERT(custom_sprite_region_owner(rows, zones, x - 1, y - 1) == hand, "[hand] must own its own pixels in view [direction].")
	var/obj/item/bodypart/arm = human.get_bodypart(BODY_ZONE_L_ARM)
	arm.drop_limb(special = TRUE)
	qdel(arm)
	zones = custom_sprite_present_regions(human)
	TEST_ASSERT(!((BODY_ZONE_L_ARM in zones) || (BODY_ZONE_PRECISE_L_HAND in zones)), "A missing arm takes its hand region with it.")
	TEST_ASSERT((BODY_ZONE_PRECISE_R_HAND in zones), "The other arm keeps its hand.")

/datum/unit_test/custom_sprite_region_map_taur/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human/consistent)
	TEST_ASSERT(custom_sprite_test_taur(human), "The fixture needs a real taur organ.")
	var/list/zones = custom_sprite_present_regions(human)
	TEST_ASSERT(!((BODY_ZONE_L_LEG in zones) || (BODY_ZONE_R_LEG in zones)), "Invisible taur legs have no region.")
	TEST_ASSERT(zones[length(zones)] == CUSTOM_MARKING_ZONE_TAUR, "The taur region comes last.")
	var/list/map = custom_sprite_region_map(human, zones, CUSTOM_SPRITE_TAUR_WIDTH)
	var/index = "[length(zones)]"
	var/owned = FALSE
	for(var/direction in map)
		TEST_ASSERT(length(map[direction][1]) == CUSTOM_SPRITE_TAUR_WIDTH, "Taur maps are 64 pixels wide.")
		for(var/row in map[direction])
			owned ||= !!findtext(row, index)
	TEST_ASSERT(owned, "The taur region must own pixels.")

/datum/unit_test/custom_sprite_region_mask/Run()
	var/list/map = list("2" = list("0120" + repeat_string(28, "0")))
	var/list/mask = custom_sprite_region_mask(map)
	TEST_ASSERT(mask["2"][1] == "0110" + repeat_string(28, "0"), "Every owned pixel is paintable; unowned pixels aren't.")
	var/list/bounds = custom_sprite_mask_bounds(mask, 32)
	TEST_ASSERT(json_encode(bounds["2"]) == json_encode(list(0, 0, 3, 1)), "Mask bounds pad the painted box by one pixel.")
	TEST_ASSERT(custom_marking_partner(BODY_ZONE_L_ARM) == BODY_ZONE_PRECISE_L_HAND && custom_marking_partner(BODY_ZONE_PRECISE_R_HAND) == BODY_ZONE_R_ARM && !custom_marking_partner(BODY_ZONE_CHEST), "Arms and hands pair up; other regions have no partner.")
