/datum/unit_test/sprite_editor_validation/Run()
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 2, 2, 4)
	var/list/valid = list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(0, 0)))
	for(var/bad_layer in list(0, 2, 1.5, "1"))
		var/list/transaction = deep_copy_list(valid)
		transaction["layer"] = bad_layer
		TEST_ASSERT(!workspace.can_transact(transaction), "Accepted invalid layer [bad_layer].")
	var/list/transaction = deep_copy_list(valid)
	transaction["dir"] = "3"
	TEST_ASSERT(!workspace.can_transact(transaction), "Accepted an unavailable direction.")
	transaction = deep_copy_list(valid)
	transaction["points"] = list(list(0, 0), list(0, 0), list(0, 0), list(0, 0), list(0, 0))
	TEST_ASSERT(!workspace.can_transact(transaction), "Accepted more points than canvas pixels.")
	for(var/list/bad_point as anything in list(list("0", 0), list(0.5, 0), list(0), list(0, 0, "forged undo")))
		transaction = deep_copy_list(valid)
		transaction["points"] = list(bad_point)
		TEST_ASSERT(!workspace.can_transact(transaction), "Accepted malformed coordinates [json_encode(bad_point)].")
	transaction = deep_copy_list(valid)
	transaction["points"] = list(list(-1, 0), list(0, 0), list(2, 0))
	TEST_ASSERT(!(!workspace.can_transact(transaction) || length(transaction["points"]) != 1), "A stroke crossing the canvas edge must retain only its in-bounds pixels.")
	transaction = list("type" = "bucket", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "point" = list(-1, 0))
	TEST_ASSERT(!workspace.can_transact(transaction), "Accepted an out-of-bounds fill seed.")
	TEST_ASSERT(!workspace.can_transact(list("type" = "flattenLayer", "layer" = 1)), "Accepted flattening the bottom layer.")
	TEST_ASSERT(!workspace.can_transact(list("type" = "deleteLayer", "layer" = 1)), "Accepted deleting the final layer.")

/datum/unit_test/sprite_editor_history/Run()
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 2, 2, 4, "#123456", SPRITE_EDITOR_COLOR_MODE_RGB, SPRITE_EDITOR_ALLOW_UNDO, SPRITE_EDITOR_TOOL_PENCIL)
	var/datum/sprite_editor_workspace/copied = workspace.copy()
	allocated += copied
	TEST_ASSERT(!(copied.backdrop != workspace.backdrop || copied.color_mode != workspace.color_mode || copied.config_flags != workspace.config_flags || copied.tool_flags != workspace.tool_flags), "Copy changed workspace configuration.")
	for(var/x in 0 to 1)
		workspace.new_transaction(list("type" = "pencil", "name" = "Forged history", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(x, 0))))
	TEST_ASSERT(workspace.undo_names[1] == "Pencil", "History names must be derived on the server.")
	workspace.undo(2)
	TEST_ASSERT(!(length(workspace.undo_stack) || length(workspace.redo_stack) != 2), "Undo did not honor its count.")
	workspace.redo(100)
	TEST_ASSERT(!(length(workspace.undo_stack) != 2 || length(workspace.redo_stack)), "Redo did not clamp its count to the available history.")
	var/list/frame = workspace.get_first_layer_pixel_data()
	TEST_ASSERT(!(frame[1][1] != "#ffffffff" || frame[1][2] != "#ffffffff"), "Redo did not restore both painted pixels.")

/datum/unit_test/custom_sprite_taur_workspace/Run()
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ff0000"), null, null, 64)
	TEST_ASSERT(!(workspace.width != 64 || workspace.height != 32), "The taur workspace must expose a bounded 64 by 32 canvas.")
	TEST_ASSERT(workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ff0000ff", "points" = list(list(63, 31)))), "The last pixel of a wide canvas must be paintable.")
	var/list/saved = workspace.serialize_drawing()
	TEST_ASSERT(!(saved?["version"] != 3 || custom_sprite_decode_grid(saved?["dirs"]?["2"], 1, 2048) != "[repeat_string(2047, "0")]1"), "Serialization must preserve the wide canvas's bottom-right pixel.")
	var/datum/sprite_editor_workspace/custom_sprite/reloaded = allocate(/datum/sprite_editor_workspace/custom_sprite, saved, list(), null, null)
	TEST_ASSERT(!(reloaded.width != 64 || reloaded.get_first_layer_pixel_data()[32][64] != "#ff0000ff"), "A saved wide drawing must select its own width when reopened.")
	TEST_ASSERT(workspace.new_transaction(list("type" = "move", "layer" = 1, "dir" = "2", "rect" = list(63, 31, 63, 31), "offset" = list(-1, 0))), "Selection movement must work in the outer half of a wide canvas.")
	workspace.undo()
	TEST_ASSERT(workspace.get_first_layer_pixel_data()[32][64] == "#ff0000ff", "Undo must restore outer canvas paint after a selection move.")
	TEST_ASSERT(!(!workspace.clear_direction("2") || workspace.serialize_drawing()), "Clear must erase the outer half of the wide canvas.")
	workspace.undo()
	TEST_ASSERT(workspace.get_first_layer_pixel_data()[32][64] == "#ff0000ff", "Undo must restore an outer canvas pixel erased by Clear.")
	var/list/legacy = list("version" = 1, "palette" = list("#00ff00"), "dirs" = list("2" = "f1[repeat_string(1023, "0")]"))
	var/datum/sprite_editor_workspace/custom_sprite/centered = allocate(/datum/sprite_editor_workspace/custom_sprite, legacy, list(), null, null, 64)
	TEST_ASSERT(!(centered.get_first_layer_pixel_data()[1][17] != "#00ff00ff" || centered.get_first_layer_pixel_data()[1][1] != "#00000000"), "Opening legacy art on a wide canvas must center it without changing body coordinates.")
	var/before = custom_sprite_hash(workspace.serialize_drawing())
	TEST_ASSERT(workspace.replace_drawing(legacy, null, "Import"), "A legacy import must replace a wide drawing as one history action.")
	TEST_ASSERT(!(workspace.get_first_layer_pixel_data()[1][17] != "#00ff00ff" || workspace.get_first_layer_pixel_data()[32][64] != "#00000000"), "Replacement must center legacy paint and clear old outer canvas pixels.")
	workspace.undo()
	TEST_ASSERT(custom_sprite_hash(workspace.serialize_drawing()) == before, "Undo must exactly restore the wide drawing before a legacy import.")
	workspace.redo()
	TEST_ASSERT(workspace.get_first_layer_pixel_data()[1][17] == "#00ff00ff", "Redo must restore the centered legacy import.")
	var/datum/sprite_editor_workspace/custom_sprite/narrow = allocate(/datum/sprite_editor_workspace/custom_sprite, legacy, list(), null, null)
	var/narrow_before = custom_sprite_hash(narrow.serialize_drawing())
	TEST_ASSERT(!(narrow.replace_drawing(saved, null, "Import") || custom_sprite_hash(narrow.serialize_drawing()) != narrow_before || length(narrow.undo_stack)), "Wide replacement into a narrow workspace must reject without cropping or adding history.")

/datum/unit_test/custom_sprite_workspace/Run()
	var/list/bounds = list("2" = list(10, 10, 20, 20))
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ffffff"), bounds)
	TEST_ASSERT(!(workspace.can_transact(list("type" = "addLayer")) || workspace.is_valid_color("#ff0000ff") || workspace.is_valid_color("#ffffff80")), "Drawing tools must enforce a single layer and opaque sampled shades.")
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(9, 10), list(10, 10))))
	var/list/drawing = workspace.serialize_drawing()
	var/grid = custom_sprite_decode_grid(drawing?["dirs"]?["2"], 1)
	TEST_ASSERT(!(!grid || copytext(grid, 331, 332) != "1" || copytext(grid, 330, 331) != "0"), "The server must clip a stroke to the selected body's bounds.")
	workspace.new_transaction(list("type" = "bucket", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "point" = list(11, 10)))
	var/list/frame = workspace.get_first_layer_pixel_data()
	TEST_ASSERT(!(frame[21][21] != "#ffffffff" || frame[22][22] != "#00000000"), "Bucket fill must obey the same bounds as a pencil.")
	workspace.clear_direction("2")
	TEST_ASSERT(!workspace.serialize_drawing(), "Clear should remove the direction.")
	workspace.undo()
	TEST_ASSERT(workspace.serialize_drawing(), "Clear must remain undoable.")

/datum/unit_test/custom_sprite_workspace_palette/Run()
	var/list/drawing = list("version" = 1, "palette" = list("#123456", "#999999"), "dirs" = list("2" = custom_sprite_encode_grid("1" + repeat_string(1023, "0"))))
	var/list/palette = list()
	for(var/i in 1 to 16)
		palette += rgb(i, 0, 0)
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, drawing, palette, null)
	for(var/i in 1 to 16)
		TEST_ASSERT(workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "[palette[i]]ff", "points" = list(list(i, 0)))), "A saved drawing must allow all 16 newly available colors.")
	var/list/saved = workspace.serialize_drawing()
	TEST_ASSERT(!(saved?["version"] != 2 || length(saved?["palette"]) != 17 || ("#999999" in saved?["palette"])), "Save must retain all used colors and omit unused stored colors.")
	var/datum/sprite_editor_workspace/custom_sprite/reloaded = allocate(/datum/sprite_editor_workspace/custom_sprite, saved, list("#ffffff"), null)
	var/list/frame = reloaded.get_first_layer_pixel_data()
	TEST_ASSERT(!(frame[1][1] != "#123456ff" || frame[1][17] != "#100000ff" || !reloaded.is_valid_color("#ffffffff")), "Reloading must preserve old pixels and allow the current palette.")
	TEST_ASSERT(!(!reloaded.update_palette(list("#abcdef")) || !reloaded.is_valid_color("#abcdefff") || reloaded.is_valid_color("#ffffffff")), "Updating available colors must replace unused shades while retaining painted colors.")
	var/datum/sprite_editor_workspace/custom_sprite/history = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#123456"), null)
	history.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#123456ff", "points" = list(list(0, 0))))
	history.undo()
	history.update_palette(list("#abcdef"))
	history.redo()
	var/list/restored = history.serialize_drawing()
	TEST_ASSERT(!(!history.is_valid_color("#123456ff") || restored?["palette"]?[1] != "#123456" || custom_sprite_decode_grid(restored?["dirs"]?["2"], 1) != "1" + repeat_string(1023, "0")), "Redo after removing a swatch must preserve its original painted color when saving.")

/datum/unit_test/custom_sprite_workspace_color_normalization/Run()
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#abcdef", "#123456"), null)
	var/list/frame = workspace.get_first_layer_pixel_data()
	frame[1][1] = "#ABCDEFff"
	frame[1][2] = "#123456ff"
	frame[1][3] = "#abcdefFF"
	frame[1][4] = "#12345600"
	frame[1][5] = null
	workspace.update_edited_direction("2")
	var/list/saved = workspace.serialize_drawing()
	TEST_ASSERT(!(json_encode(saved?["palette"]) != json_encode(list("#abcdef", "#123456")) || custom_sprite_decode_grid(saved?["dirs"]?["2"], 2) != "121[repeat_string(1021, "0")]"), "Repeated shades must normalize once without changing first-use order or making transparent pixels opaque.")

/datum/unit_test/custom_sprite_workspace_history_palette_limit/Run()
	var/list/palette = list()
	for(var/i in 1 to 63)
		palette += rgb(i, 0, 0)
	var/grid = "123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_" + repeat_string(961, "0")
	var/list/drawing = list("version" = 2, "palette" = palette, "dirs" = list("2" = custom_sprite_encode_grid(grid, 63)))
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, drawing, palette, null)
	workspace.new_transaction(list("type" = "eraser", "layer" = 1, "dir" = "2", "points" = list(list(0, 0))))
	TEST_ASSERT(!workspace.update_palette(list("#ffffff")), "Erasing a color cannot free its palette capacity while undo can restore it.")
	workspace.undo()
	TEST_ASSERT(!workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(31, 31)))), "Undo must not allow painting a sixty-fourth color.")
	var/list/saved = workspace.serialize_drawing()
	TEST_ASSERT(!(!saved || length(saved["palette"]) != 63 || custom_sprite_decode_grid(saved["dirs"]["2"], 63) != grid), "Undo and palette changes must not turn a full drawing into an empty save.")

/datum/unit_test/custom_sprite_clear_history/Run()
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ffffff"), null)
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(0, 0), list(31, 31))))
	workspace.undo()
	TEST_ASSERT(!(workspace.clear_direction("2") || length(workspace.undo_stack) || length(workspace.redo_stack) != 1), "Clearing an empty direction must preserve redo without creating history.")
	workspace.redo()
	workspace.draw_bounds = list("2" = list(10, 10, 20, 20))
	TEST_ASSERT(!(!workspace.clear_direction("2") || workspace.serialize_drawing()), "Clear must erase old pixels outside the current draw bounds.")
	var/list/clear = workspace.undo_stack[length(workspace.undo_stack)]
	TEST_ASSERT(length(clear["points"]) == 2, "Clear must store only the two painted pixels in undo history.")
	workspace.undo()
	var/list/frame = workspace.get_first_layer_pixel_data()
	TEST_ASSERT(!(frame[1][1] != "#ffffffff" || frame[32][32] != "#ffffffff" || workspace.is_point_allowed(0, 0, "2")), "Undo Clear must restore both pixels while retaining the new drawing bounds.")

/datum/unit_test/sprite_editor_layer_history/Run()
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 2, 2, 4, null, SPRITE_EDITOR_COLOR_MODE_RGBA, ALL, ALL, "#00000000")
	workspace.new_transaction(list("type" = "addLayer", "points" = list("unrelated metadata"), "oldLayer" = list("forged")))
	TEST_ASSERT(length(workspace.undo_stack[1]) == 2, "History must discard fields unrelated to the validated transaction.")
	workspace.new_transaction(list("type" = "pencil", "layer" = 2, "dir" = "8", "color" = "#ffffffff", "points" = list(list(1, 1))))
	workspace.new_transaction(list("type" = "flattenLayer", "layer" = 2))
	TEST_ASSERT(!(length(workspace.layers) != 1 || workspace.layers[1]["data"]["8"][2][2] != "#ffffffff"), "Flatten must blend the actual direction frames.")
	workspace.undo()
	TEST_ASSERT(!(length(workspace.layers) != 2 || workspace.layers[1]["data"]["8"][2][2] != "#00000000" || workspace.layers[2]["data"]["8"][2][2] != "#ffffffff"), "Undo flatten must restore two independent layer records.")
	workspace.new_transaction(list("type" = "deleteLayer", "layer" = 2))
	workspace.undo()
	TEST_ASSERT(!(length(workspace.layers) != 2 || workspace.layers[2]["data"]["8"][2][2] != "#ffffffff"), "Undo delete must restore the entire layer.")

/datum/unit_test/custom_sprite_selection_move/Run()
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ff0000", "#00ff00", "#0000ff"), null)
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ff0000ff", "points" = list(list(0, 0))))
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#00ff00ff", "points" = list(list(1, 0))))
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#0000ffff", "points" = list(list(3, 0))))
	var/before = json_encode(workspace.serialize_drawing())
	var/list/move = list("type" = "move", "name" = "Forged", "layer" = 1, "dir" = "2", "rect" = list(0, 0, 2, 0), "offset" = list(1, 0), "points" = list(list(31, 31, "forged", "#ffffffff")))
	TEST_ASSERT(workspace.new_transaction(move), "A valid overlapping selection move must be accepted.")
	var/list/frame = workspace.get_first_layer_pixel_data()
	TEST_ASSERT(!(frame[1][1] != "#00000000" || frame[1][2] != "#ff0000ff" || frame[1][3] != "#00ff00ff" || frame[1][4] != "#0000ffff" || frame[32][32] != "#00000000"), "Move must snapshot overlaps, clear its source, ignore transparent source pixels, and discard forged patches.")
	TEST_ASSERT(!(length(workspace.undo_stack) != 4 || workspace.undo_names[4] != "Move selection" || length(workspace.undo_stack[4]["points"]) != 3), "A move must create one canonical history entry containing only changed pixels.")
	var/after = json_encode(workspace.serialize_drawing())
	workspace.undo()
	TEST_ASSERT(json_encode(workspace.serialize_drawing()) == before, "Undo must restore the complete pre-move drawing.")
	workspace.update_palette(list())
	workspace.redo()
	TEST_ASSERT(!(json_encode(workspace.serialize_drawing()) != after || length(workspace.palette) != 3 || workspace.edited_directions["1"]), "Redo must preserve exact colors and direction isolation after palette refresh.")
	var/datum/sprite_editor_workspace/custom_sprite/reopened = allocate(/datum/sprite_editor_workspace/custom_sprite, workspace.serialize_drawing(), list(), null)
	TEST_ASSERT(json_encode(reopened.get_first_layer_pixel_data()) == json_encode(frame), "Saving and reopening must preserve moved pixels exactly.")
	workspace.new_transaction(list("type" = "move", "layer" = 1, "dir" = "2", "rect" = list(1, 0, 2, 0), "offset" = list(0, 1)))
	TEST_ASSERT(!(frame[1][2] != "#00000000" || frame[2][2] != "#ff0000ff" || frame[2][3] != "#00ff00ff"), "Vertical moves must use the same top-left canvas coordinates as strokes.")

/datum/unit_test/custom_sprite_selection_move_validation/Run()
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ffffff"), list("2" = list(10, 10, 20, 20)))
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(10, 10))))
	workspace.undo()
	var/list/valid = list("type" = "move", "layer" = 1, "dir" = "2", "rect" = list(10, 10, 11, 11), "offset" = list(1, 0))
	var/list/invalid = list(
		list("rect" = list(10, 10, 11)),
		list("rect" = list(10, 10, 9, 11)),
		list("rect" = list(10, 10, 32, 11)),
		list("rect" = list(10, 10, 11.5, 11)),
		list("rect" = list("10", 10, 11, 11)),
		list("rect" = list(-1, 10, 11, 11)),
		list("offset" = list(10, 0)),
		list("offset" = list(-11, 0)),
		list("offset" = list(0.5, 0)),
		list("offset" = list("1", 0)),
		list("offset" = list(1, 0, 0)),
		list("offset" = list(1000000, 0)),
		list("dir" = "3"),
		list("dir" = 2),
		list("layer" = 1.5),
		list("layer" = 2),
	)
	for(var/list/replacement as anything in invalid)
		var/list/transaction = deep_copy_list(valid)
		for(var/key, value in replacement)
			transaction[key] = value
		TEST_ASSERT(!workspace.new_transaction(transaction), "Rejected move metadata must not enter history: [json_encode(replacement)].")
	TEST_ASSERT(!(workspace.new_transaction(deep_copy_list(valid)) || length(workspace.undo_stack) || length(workspace.redo_stack) != 1), "Empty moves and malformed moves must preserve redo without recording history.")
	workspace.redo()
	valid["offset"] = list(0, 0)
	TEST_ASSERT(!(workspace.new_transaction(deep_copy_list(valid)) || length(workspace.undo_stack) != 1), "Zero displacement must not create a transaction.")
	TEST_ASSERT((workspace.tool_flags & 16), "Custom workspaces must advertise the Select tool.")

/datum/unit_test/custom_sprite_selection_shaded_margin/Run()
	var/list/rows = list()
	for(var/y in 0 to 31)
		rows += y == 10 ? "[repeat_string(10, "0")]111[repeat_string(19, "0")]" : repeat_string(32, "0")
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ff0000", "#0000ff"), list("2" = list(10, 10, 20, 20)), list("2" = rows))
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ff0000ff", "points" = list(list(10, 10))))
	var/list/frame = workspace.get_first_layer_pixel_data()
	frame[10][10] = "#0000ffff"
	var/before = json_encode(frame)
	var/list/move = list("type" = "move", "layer" = 1, "dir" = "2", "rect" = list(9, 9, 10, 10), "offset" = list(1, 0))
	TEST_ASSERT(!(workspace.new_transaction(deep_copy_list(move)) || json_encode(frame) != before), "Hidden paint in a selection must not be dragged into another shaded pixel.")
	move["rect"] = list(10, 9, 10, 10)
	TEST_ASSERT(!(!workspace.new_transaction(deep_copy_list(move)) || frame[11][11] != "#00000000" || frame[11][12] != "#ff0000ff" || frame[10][10] != "#0000ffff"), "A selection starting in shaded margins must move allowed paint.")
	var/after = json_encode(frame)
	workspace.undo()
	TEST_ASSERT(json_encode(frame) == before, "Undo must restore the exact frame, including hidden pixels.")
	workspace.redo()
	TEST_ASSERT(json_encode(frame) == after, "Redo must restore the shaded-margin move exactly.")
	move["rect"] = list(9, 9, 11, 10)
	for(var/list/offset as anything in list(list(-2, 0), list(2, 0), list(1, 1), list(-10, 0), list(21, 0)))
		move["offset"] = offset
		TEST_ASSERT(!(workspace.new_transaction(deep_copy_list(move)) || json_encode(frame) != after || length(workspace.undo_stack) != 2), "Selection margins must not permit paint outside bounds or masks, or a box outside the canvas.")
	TEST_ASSERT(!(!workspace.new_transaction(list("type" = "move", "layer" = 1, "dir" = "2", "rect" = list(9, 9, 9, 9), "offset" = list(1, 1))) || frame[10][10] != "#00000000" || frame[11][11] != "#0000ffff"), "Hidden paint must be movable back inside the bounds.")

/datum/unit_test/sprite_editor_selection_move/Run()
	var/obj/item/canvas/canvas = allocate(/obj/item/canvas)
	TEST_ASSERT(!(!(canvas.workspace.tool_flags & 16) || (canvas.workspace.tool_flags & SPRITE_EDITOR_TOOL_ERASER) || canvas.workspace.config_flags), "Canvas must enable Select while preserving its other tool and history restrictions.")
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 4, 4, 4, null, SPRITE_EDITOR_COLOR_MODE_RGBA, ALL, ALL, "#00000000")
	workspace.new_transaction(list("type" = "addLayer"))
	workspace.new_transaction(list("type" = "pencil", "layer" = 2, "dir" = "8", "color" = "#ff000080", "points" = list(list(0, 0))))
	workspace.new_transaction(list("type" = "pencil", "layer" = 2, "dir" = "8", "color" = "#00ff00ff", "points" = list(list(1, 0))))
	var/before = json_encode(workspace.layers)
	TEST_ASSERT(workspace.new_transaction(list("type" = "move", "layer" = 2, "dir" = "8", "rect" = list(0, 0, 0, 0), "offset" = list(1, 0))), "Generic painting workspaces must accept selection movement.")
	TEST_ASSERT(!(workspace.layers[2]["data"]["8"][1][2] != "#ff000080" || workspace.layers[2]["data"]["8"][1][1] != "#00000000" || workspace.layers[1]["data"]["8"][1][2] != "#00000000" || workspace.layers[2]["data"]["2"][1][2] != "#00000000"), "Move must replace translucent pixels exactly, without blending or changing other layers/directions.")
	workspace.undo()
	TEST_ASSERT(json_encode(workspace.layers) == before, "Undo must restore overwritten destination pixels and the source alpha.")
	workspace.tool_flags = SPRITE_EDITOR_TOOL_PENCIL
	TEST_ASSERT(!(workspace.new_transaction(list("type" = "move", "layer" = 2, "dir" = "8", "rect" = list(0, 0, 0, 0), "offset" = list(1, 0))) || length(workspace.redo_stack) != 1), "Workspaces without the Select flag must reject moves without losing redo.")
	workspace.tool_flags = ALL
	var/list/frame = workspace.layers[2]["data"]["8"]
	frame[3][1] = "#000000"
	frame[3][2] = "#12345600"
	frame[3][3] = "#ffffffff"
	frame[3][4] = "#0000ffff"
	TEST_ASSERT(!(!workspace.new_transaction(list("type" = "move", "layer" = 2, "dir" = "8", "rect" = list(0, 2, 1, 2), "offset" = list(2, 0))) || frame[3][3] != "#000000" || frame[3][4] != "#0000ffff"), "Six-digit RGB black is opaque; colored zero-alpha pixels must not replace the destination.")

/datum/unit_test/custom_sprite_limb_mask/Run()
	var/list/rows = list("1011[repeat_string(28, "0")]")
	for(var/y in 2 to 32)
		rows += repeat_string(32, "0")
	var/list/mask = list("2" = rows)
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ff0000", "#0000ff"), null, mask)
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ff0000ff", "points" = list(list(0, 0), list(1, 0))))
	var/list/frame = workspace.get_first_layer_pixel_data()
	TEST_ASSERT(!(frame[1][1] != "#ff0000ff" || frame[1][2] != "#00000000"), "Pencil must clip points in silhouette holes.")
	// Old pixels can remain outside a changed species' mask. They can be erased or moved back on, never painted.
	frame[1][2] = "#0000ffff"
	workspace.new_transaction(list("type" = "eraser", "layer" = 1, "dir" = "2", "points" = list(list(1, 0), list(4, 0))))
	TEST_ASSERT(frame[1][2] == "#00000000", "Erasing must remove existing paint outside the limb mask.")
	TEST_ASSERT(!(workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ff0000ff", "points" = list(list(1, 0)))) || frame[1][2] != "#00000000"), "Painting outside the mask must stay blocked after erasing there.")
	frame[1][2] = "#0000ffff"
	var/list/move = list("type" = "move", "layer" = 1, "dir" = "2", "rect" = list(0, 0, 1, 0), "offset" = list(1, 0))
	TEST_ASSERT(!workspace.new_transaction(deep_copy_list(move)), "Selection must reject moving painted pixels off the limb.")
	move["offset"] = list(2, 0)
	TEST_ASSERT(!(!workspace.new_transaction(move) || frame[1][1] != "#00000000" || frame[1][2] != "#00000000" || frame[1][3] != "#ff0000ff" || frame[1][4] != "#0000ffff"), "Selection must carry hidden paint back onto the limb.")
	workspace.undo()
	TEST_ASSERT(!(frame[1][1] != "#ff0000ff" || frame[1][2] != "#0000ffff" || frame[1][3] != "#00000000" || frame[1][4] != "#00000000"), "Undo must restore mask-aware moves exactly.")
	workspace.clear_direction("2")
	TEST_ASSERT(!(workspace.edited_directions["2"] || workspace.draw_mask != mask), "Clear must remove stale out-of-mask pixels and restore the mask.")
	workspace.new_transaction(list("type" = "bucket", "layer" = 1, "dir" = "2", "color" = "#ff0000ff", "point" = list(0, 0)))
	TEST_ASSERT(!(frame[1][1] != "#ff0000ff" || frame[1][3] != "#00000000" || frame[1][4] != "#00000000"), "Fill must stop at silhouette holes instead of reaching disconnected pixels through the backdrop.")
	for(var/y in 0 to 31)
		for(var/x in 0 to 31)
			TEST_ASSERT(!(!workspace.is_point_allowed(x, y, "2") && frame[y + 1][x + 1] != "#00000000"), "Fill must never paint outside the limb silhouette.")
	TEST_ASSERT(!workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "1", "color" = "#ff0000ff", "points" = list(list(0, 0)))), "An absent direction mask must reject paint.")

/// A region workspace over two regions on the first row: "1" at x 0-3, "2" at x 4-7.
/proc/custom_sprite_test_region_workspace()
	var/datum/sprite_editor_workspace/custom_sprite/regions/workspace = new(null, list("#ffffff", "#123456"), null, null, 32)
	workspace.region_map = custom_sprite_test_region_rows("11112222")
	workspace.draw_mask = custom_sprite_region_mask(workspace.region_map)
	workspace.draw_bounds = custom_sprite_mask_bounds(workspace.draw_mask, 32)
	return workspace

/datum/unit_test/custom_sprite_region_workspace/Run()
	var/datum/sprite_editor_workspace/custom_sprite/regions/workspace = custom_sprite_test_region_workspace()
	TEST_ASSERT(!(workspace.is_point_allowed(8, 0, "2") || !workspace.is_point_allowed(7, 0, "2")), "Only region pixels are paintable.")
	TEST_ASSERT(workspace.new_transaction(list("type" = "bucket", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "point" = list(1, 0))), "Filling a region must succeed.")
	var/list/row = workspace.layers[1]["data"]["2"][1]
	TEST_ASSERT(!(row[4] != "#ffffffff" || row[5] != "#00000000"), "Fill must stop at the region edge.")
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#123456ff", "points" = list(list(5, 0))))
	TEST_ASSERT(!workspace.new_transaction(list("type" = "eraser", "layer" = 1, "dir" = "2", "points" = list(list(20, 0)))), "The eraser can't reach outside the regions either.")
	TEST_ASSERT(workspace.clear_region("2", "1"), "Clearing a painted region must succeed.")
	TEST_ASSERT(!(row[1] != "#00000000" || row[6] != "#123456ff"), "Clear must erase only the chosen region.")
	workspace.undo()
	TEST_ASSERT(row[1] == "#ffffffff", "Undo must restore a cleared region.")
	qdel(workspace)

/datum/unit_test/custom_sprite_region_workspace_replace/Run()
	var/datum/sprite_editor_workspace/custom_sprite/regions/workspace = custom_sprite_test_region_workspace()
	workspace.markings_context = list(BODY_ZONE_L_ARM = list())
	workspace.emissive = list(BODY_ZONE_L_ARM = custom_sprite_emissive_settings(FALSE))
	var/list/frames = deep_copy_list(workspace.layers[1]["data"])
	frames["2"][1][2] = "#ffffffff"
	var/list/markings = list(BODY_ZONE_L_ARM = list(list("name" = "Stripe", "color" = "#112233", "emissive" = FALSE)))
	var/list/emissive = list(BODY_ZONE_L_ARM = custom_sprite_emissive_settings(TRUE))
	TEST_ASSERT(workspace.replace_frames(frames, "Import style", markings, emissive), "Replacing the canvas must succeed.")
	TEST_ASSERT(!(workspace.layers[1]["data"]["2"][1][2] != "#ffffffff" || json_encode(workspace.markings_context) != json_encode(markings) || json_encode(workspace.emissive) != json_encode(emissive)), "Replacement must apply pixels, base markings and emission together.")
	workspace.undo()
	TEST_ASSERT(!(workspace.layers[1]["data"]["2"][1][2] != "#00000000" || length(workspace.markings_context[BODY_ZONE_L_ARM]) || workspace.emissive[BODY_ZONE_L_ARM]["2"]), "Undo must restore all three.")
	workspace.load_frames(frames)
	TEST_ASSERT(!(!workspace.edited_directions["2"] || !("#ffffff" in workspace.palette)), "Loading frames must mark edited views and admit their colors.")
	qdel(workspace)
