#if defined(UNIT_TESTS) || defined(SPACEMAN_DMM)

/datum/unit_test/custom_sprite_codec/Run()
	var/empty_grid = repeat_string(1024, "0")
	var/solid_grid = repeat_string(1024, "1")
	var/alternating = repeat_string(512, "12")
	for(var/grid in list(empty_grid, solid_grid, alternating))
		var/encoded = custom_sprite_encode_grid(grid)
		if(length(encoded) > 1025 || custom_sprite_decode_grid(encoded, 2) != grid)
			Fail("Encoding must round-trip within the flat size bound.", __FILE__, __LINE__)
		if(custom_sprite_decode_grid("f[grid]", 2) != grid)
			Fail("The flat representation must decode identically.", __FILE__, __LINE__)
	if(copytext(custom_sprite_encode_grid(solid_grid), 1, 2) != "r")
		Fail("A solid canvas should use RLE.", __FILE__, __LINE__)
	if(custom_sprite_encode_grid(alternating) != "f[alternating]")
		Fail("Worst-case alternating pixels should use the flat fallback.", __FILE__, __LINE__)
	if(custom_sprite_encode_grid(repeat_string(1024, "A")) || custom_sprite_decode_grid("f[repeat_string(1024, "A")]", 15))
		Fail("Grid indices must use lowercase hex.", __FILE__, __LINE__)
	for(var/bad in list("", "x[solid_grid]", "f1", "r01", "r11", "r111", "rz1", "f[repeat_string(1024, "g")]", "f[repeat_string(1024, "3")]", "r[repeat_string(69, "f1")]"))
		if(!isnull(custom_sprite_decode_grid(bad, 2)))
			Fail("Accepted a malformed grid: [copytext(bad, 1, 20)].", __FILE__, __LINE__)
	if(custom_sprite_decode_grid("r[repeat_string(68, "f1")]4g", 15) || custom_sprite_decode_grid("f[repeat_string(1023, "1")]g", 15))
		Fail("Both representations must reject an invalid index at the end of an otherwise valid grid.", __FILE__, __LINE__)
	if(custom_sprite_decode_grid("r[repeat_string(68, "f1")]41", 1) != solid_grid)
		Fail("RLE validation must still accept an exact 1,024-pixel run boundary.", __FILE__, __LINE__)
	var/list/drawing = list("version" = 1, "palette" = list("#FFFFFF", "#b0b0b0"), "tint" = null, "dirs" = list("2" = "f[solid_grid]", "1" = "r01"))
	var/list/validated = custom_sprite_validate(drawing)
	if(!validated || validated["palette"][1] != "#ffffff" || length(validated["dirs"]) != 1 || !validated["dirs"]["2"])
		Fail("A corrupt direction must not discard a valid direction.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_codec_canonical_runs/Run()
	var/list/cases = list(
		"[repeat_string(15, "1")][repeat_string(1009, "0")]" = "rf1[repeat_string(67, "f0")]40",
		"[repeat_string(16, "1")][repeat_string(1008, "0")]" = "rf111[repeat_string(67, "f0")]30",
		"[repeat_string(31, "1")][repeat_string(993, "0")]" = "rf1f111[repeat_string(66, "f0")]30",
	)
	for(var/grid in cases)
		if(custom_sprite_encode_grid(grid, 1) != cases[grid] || custom_sprite_decode_grid(cases[grid], 1) != grid)
			Fail("Runs crossing the 15-pixel limit must retain their exact saved representation.", __FILE__, __LINE__)
	var/late_invalid = "[repeat_string(511, "12")]1!"
	if(custom_sprite_encode_grid(late_invalid, 2) || custom_sprite_decode_grid("f[late_invalid]", 2))
		Fail("A flat fallback must still reject an invalid final pixel.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_extended_palette/Run()
	var/list/palette = list()
	for(var/i in 1 to 63)
		palette += rgb(i, 0, 0)
	var/grid = "123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_" + repeat_string(961, "0")
	var/encoded = custom_sprite_encode_grid(grid, 63)
	if(custom_sprite_decode_grid(encoded, 63) != grid)
		Fail("All 63 opaque colors must round-trip without changing indices.", __FILE__, __LINE__)
	var/list/drawing = list("version" = 2, "palette" = palette, "dirs" = list("2" = encoded))
	if(!custom_sprite_validate(drawing))
		Fail("Version 2 must preserve palettes larger than 15 colors.", __FILE__, __LINE__)
	drawing["version"] = 1
	if(custom_sprite_validate(drawing))
		Fail("Version 1 must retain its 15-color limit.", __FILE__, __LINE__)
	for(var/size in list(0, 1.5, 64, "16"))
		if(custom_sprite_decode_grid(encoded, size))
			Fail("Invalid palette sizes must be rejected.", __FILE__, __LINE__)
	if(custom_sprite_decode_grid("f[repeat_string(1024, "!")]", 63) || custom_sprite_decode_grid("rg1", 63))
		Fail("Extended indices must not relax run-length or character validation.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_emissive_metadata/Run()
	var/list/drawing = custom_sprite_test_drawing()
	if("emissive" in drawing)
		Fail("Legacy drawings must retain an absent emissive setting for preference defaults.", __FILE__, __LINE__)
	var/pixel_hash = custom_sprite_pixel_hash(drawing)
	for(var/enabled in list(TRUE, FALSE))
		drawing["emissive"] = enabled
		var/list/clean = custom_sprite_validate(drawing)
		if(!clean || json_encode(clean["emissive"]) != json_encode(custom_sprite_emissive_settings(enabled)) || custom_sprite_pixel_hash(clean) != pixel_hash)
			Fail("Legacy booleans must migrate to all four views without changing drawing pixels.", __FILE__, __LINE__)
	for(var/bad in list(null, "true", 2, list(TRUE)))
		drawing["emissive"] = bad
		var/list/clean = custom_sprite_validate(drawing)
		if(!clean || json_encode(clean["emissive"]) != json_encode(custom_sprite_emissive_settings(FALSE)))
			Fail("Malformed optional emissive metadata must disable emission without discarding painted pixels.", __FILE__, __LINE__)
	drawing["emissive"] = list("2" = TRUE, "1" = FALSE, "4" = "true", "8" = 2, "16" = TRUE)
	var/list/clean = custom_sprite_validate(drawing)
	var/list/settings = clean["emissive"]
	if(length(settings) != 4 || !settings["2"] || settings["1"] || settings["4"] || settings["8"] || custom_sprite_pixel_hash(clean) != pixel_hash)
		Fail("Directional settings must remain bounded and admit only explicit true values.", __FILE__, __LINE__)
	if(custom_sprite_hash(clean) != custom_sprite_hash(custom_sprite_validate(clean)))
		Fail("Canonical directional metadata must retain a stable drawing hash on validation.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_taur_codec/Run()
	var/solid = repeat_string(2048, "1")
	var/alternating = repeat_string(1024, "12")
	for(var/grid in list(solid, alternating))
		var/encoded = custom_sprite_encode_grid(grid, 2, 2048)
		if(!encoded || length(encoded) > 2049 || custom_sprite_decode_grid(encoded, 2, 2048) != grid)
			Fail("Wide grids must round-trip within the 2,049-character bound.", __FILE__, __LINE__)
		if(custom_sprite_decode_grid("f[grid]", 2, 2048) != grid || custom_sprite_decode_grid("f[grid]", 2))
			Fail("Wide flat data must require an explicit 2,048-pixel canvas.", __FILE__, __LINE__)
	if(custom_sprite_decode_grid("r[repeat_string(136, "f1")]81", 1, 2048) != solid)
		Fail("Wide RLE must accept exactly 2,048 pixels.", __FILE__, __LINE__)
	for(var/bad in list("r[repeat_string(136, "f1")]91", "r[repeat_string(136, "f1")]71", "r[repeat_string(136, "f1")]01", "f[repeat_string(2047, "1")]!", "f[repeat_string(2049, "1")]"))
		if(custom_sprite_decode_grid(bad, 2, 2048))
			Fail("Wide data must reject overflow, underflow, invalid runs and invalid indices.", __FILE__, __LINE__)
	if(custom_sprite_encode_grid("[repeat_string(1023, "12")]1!", 2, 2048))
		Fail("Wide flat fallback must validate the final index before returning.", __FILE__, __LINE__)
	for(var/bad_count in list(0, 1023, 1025, 2047, 2049, 4096, 1024.5, "2048"))
		if(custom_sprite_encode_grid(repeat_string(1024, "1"), 2, bad_count) || custom_sprite_decode_grid("f[solid]", 2, bad_count))
			Fail("Pixel counts must be limited to the two supported canvas sizes.", __FILE__, __LINE__)
	var/list/drawing = list("version" = 3, "palette" = list("#FFFFFF"), "dirs" = list("2" = "f[solid]"))
	var/list/clean = custom_sprite_validate(drawing)
	if(!clean || clean["version"] != 3 || clean["palette"][1] != "#ffffff")
		Fail("A one-color wide drawing must retain version 3 during canonical validation.", __FILE__, __LINE__)
	for(var/version in list(1, 2))
		drawing["version"] = version
		if(custom_sprite_validate(drawing))
			Fail("Legacy drawing versions must not accept wide pixel data.", __FILE__, __LINE__)
	drawing["version"] = 3
	drawing["dirs"]["2"] = "f[repeat_string(1024, "1")]"
	if(custom_sprite_validate(drawing))
		Fail("Version 3 must not accept a legacy-sized direction.", __FILE__, __LINE__)
	var/list/legacy = custom_sprite_test_drawing()
	var/list/wide_identity = deep_copy_list(legacy)
	wide_identity["version"] = 3
	if(custom_sprite_pixel_hash(legacy) == custom_sprite_pixel_hash(wide_identity))
		Fail("Pixel cache identity must include the drawing's canvas width.", __FILE__, __LINE__)
	var/list/zones = custom_limb_markings_validate(list("taur" = clean, BODY_ZONE_HEAD = legacy, BODY_ZONE_CHEST = clean))
	if(length(zones) != 2 || zones?["taur"]?["version"] != 3 || !zones?[BODY_ZONE_HEAD] || zones?[BODY_ZONE_CHEST])
		Fail("Stored zone drawings must retain valid taur and legacy art while rejecting wide ordinary-limb art.", __FILE__, __LINE__)
	if(custom_limb_markings_validate(list("taur" = legacy)))
		Fail("Stored taur-zone drawings must not accept a legacy-sized canvas.", __FILE__, __LINE__)
	legacy["tint"] = "#abcdef"
	legacy["emissive"] = custom_sprite_emissive_settings(list("2" = TRUE))
	var/before_resize = custom_sprite_hash(legacy)
	var/list/expanded = custom_sprite_resize_drawing(legacy, 64)
	if(!expanded || custom_sprite_hash(legacy) != before_resize || expanded["tint"] != "#abcdef" || !expanded["emissive"]["2"])
		Fail("Expanding legacy art must preserve its metadata without mutating the saved drawing.", __FILE__, __LINE__)
	for(var/direction in GLOB.custom_style_directions)
		if(custom_sprite_decode_grid(expanded?["dirs"]?[direction], 2, 2048) != repeat_string(32, "[repeat_string(16, "0")][repeat_string(32, "1")][repeat_string(16, "0")]"))
			Fail("Expansion must center every legacy row with exactly sixteen empty pixels on each side.", __FILE__, __LINE__)
	if(custom_sprite_resize_drawing(expanded, 32) || custom_sprite_resize_drawing(legacy, 128))
		Fail("Canvas reframing must refuse shrinking and unsupported dimensions.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_sidecar/Run()
	var/test_path = "tmp/custom_sprites_[REF(src)].json"
	text2file("invalid JSON", test_path)
	var/original_contents = file2text(test_path)
	var/datum/json_savefile/custom_sprites/store = allocate(/datum/json_savefile/custom_sprites, test_path)
	if(length(store.get_entry()))
		Fail("Corrupt sidecars must become an empty store.", __FILE__, __LINE__)
	store.set_entry("character1", list("hair" = list("version" = 1)))
	if(store.save() || !store.last_save_failed || file2text(test_path) != original_contents)
		Fail("An unreadable primary without a good backup must refuse writes and preserve its original bytes.", __FILE__, __LINE__)
	var/clean_path = "tmp/custom_sprites_clean_[REF(src)].json"
	var/datum/json_savefile/custom_sprites/clean_store = allocate(/datum/json_savefile/custom_sprites, clean_path)
	clean_store.set_entry("character1", list("hair" = list("version" = 1)))
	if(!clean_store.save())
		Fail("A new disposable sidecar must still accept valid writes.", __FILE__, __LINE__)
	fdel(test_path)
	test_path = clean_path
	var/datum/json_savefile/custom_sprites/reloaded = allocate(/datum/json_savefile/custom_sprites, test_path)
	if(json_encode(clean_store.get_entry()) != json_encode(reloaded.get_entry()))
		Fail("Sidecar did not persist its entries.", __FILE__, __LINE__)
	fdel(test_path)
	fdel("[test_path].bak")
	fdel("[test_path].new")
	var/datum/json_savefile/custom_sprites/missing = allocate(/datum/json_savefile/custom_sprites, test_path)
	if(length(missing.get_entry()))
		Fail("Missing sidecars must become an empty store.", __FILE__, __LINE__)
	for(var/bad_root in list("null", "42", "\"text\"", "\[1,2,3]"))
		fdel(test_path)
		text2file(bad_root, test_path)
		var/datum/json_savefile/custom_sprites/bad_store = allocate(/datum/json_savefile/custom_sprites, test_path)
		if(length(bad_store.get_entry()))
			Fail("Invalid roots must not create character entries.", __FILE__, __LINE__)
	fdel(test_path)

#endif
