#if defined(UNIT_TESTS) || defined(SPACEMAN_DMM)

/datum/unit_test/custom_sprite_codec/Run()
	var/empty_grid = repeat_string(1024, "0")
	var/solid_grid = repeat_string(1024, "1")
	var/alternating = repeat_string(512, "12")
	for(var/grid in list(empty_grid, solid_grid, alternating))
		var/encoded = custom_sprite_encode_grid(grid)
		if(length(encoded) > 1025 || custom_sprite_decode_grid(encoded, 2) != grid)
			Fail("Encoding must round-trip within the flat size bound.", __FILE__, __LINE__)
		if(custom_sprite_decode_grid("f[grid]", 2) != grid)
			Fail("The flat representation must decode identically.", __FILE__, __LINE__)
	if(copytext(custom_sprite_encode_grid(solid_grid), 1, 2) != "r")
		Fail("A solid canvas should use RLE.", __FILE__, __LINE__)
	if(custom_sprite_encode_grid(alternating) != "f[alternating]")
		Fail("Worst-case alternating pixels should use the flat fallback.", __FILE__, __LINE__)
	if(custom_sprite_encode_grid(repeat_string(1024, "A")) || custom_sprite_decode_grid("f[repeat_string(1024, "A")]", 15))
		Fail("Grid indices must use lowercase hex.", __FILE__, __LINE__)
	for(var/bad in list("", "x[solid_grid]", "f1", "r01", "r11", "r111", "rz1", "f[repeat_string(1024, "g")]", "f[repeat_string(1024, "3")]", "r[repeat_string(69, "f1")]"))
		if(!isnull(custom_sprite_decode_grid(bad, 2)))
			Fail("Accepted a malformed grid: [copytext(bad, 1, 20)].", __FILE__, __LINE__)
	var/list/drawing = list("version" = 1, "palette" = list("#FFFFFF", "#b0b0b0"), "tint" = null, "dirs" = list("2" = "f[solid_grid]", "1" = "r01"))
	var/list/validated = custom_sprite_validate(drawing)
	if(!validated || validated["palette"][1] != "#ffffff" || length(validated["dirs"]) != 1 || !validated["dirs"]["2"])
		Fail("A corrupt direction must not discard a valid direction.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_sidecar/Run()
	var/test_path = "tmp/custom_sprites_[REF(src)].json"
	text2file("invalid JSON", test_path)
	var/datum/json_savefile/custom_sprites/store = allocate(/datum/json_savefile/custom_sprites, test_path)
	if(length(store.get_entry()))
		Fail("Corrupt sidecars must become an empty store.", __FILE__, __LINE__)
	store.set_entry("character1", list("hair" = list("version" = 1)))
	store.save()
	var/datum/json_savefile/custom_sprites/reloaded = allocate(/datum/json_savefile/custom_sprites, test_path)
	if(json_encode(store.get_entry()) != json_encode(reloaded.get_entry()))
		Fail("Sidecar did not persist its entries.", __FILE__, __LINE__)
	fdel(test_path)
	var/datum/json_savefile/custom_sprites/missing = allocate(/datum/json_savefile/custom_sprites, test_path)
	if(length(missing.get_entry()))
		Fail("Missing sidecars must become an empty store.", __FILE__, __LINE__)
	for(var/bad_root in list("null", "42", "\"text\"", "\[1,2,3]"))
		fdel(test_path)
		text2file(bad_root, test_path)
		var/datum/json_savefile/custom_sprites/bad_store = allocate(/datum/json_savefile/custom_sprites, test_path)
		if(length(bad_store.get_entry()))
			Fail("Invalid roots must not create character entries.", __FILE__, __LINE__)
	fdel(test_path)

#endif
