#if defined(UNIT_TESTS) || defined(SPACEMAN_DMM)

/datum/unit_test/custom_sprite_direction_sampling/Run()
	var/icon/source = custom_sprite_blank_icon()
	var/list/colors = list("#ff0000", "#00ff00", "#0000ff", "#ffff00")
	var/index = 0
	for(var/direction in GLOB.cardinals)
		index++
		var/icon/frame = icon('icons/blanks/32x32.dmi', "nothing")
		frame.DrawBox(colors[index], index, index, index, index)
		source.Insert(frame, "", direction)
	index = 0
	for(var/direction in GLOB.cardinals)
		index++
		var/list/bounds = custom_sprite_icon_bounds(source, direction, 0)
		if(json_encode(bounds) != json_encode(list(index - 1, 32 - index, index - 1, 32 - index)))
			Fail("Bounds must inspect the selected direction, not the default icon frame.", __FILE__, __LINE__)
	var/list/palette = custom_sprite_sample_palette(source, "")
	if(length(palette) != 4 || length(colors - palette))
		Fail("Automatic palettes must sample colors from all four directions.", __FILE__, __LINE__)

/datum/unit_test/sprite_editor_validation/Run()
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 2, 2, 4)
	var/list/valid = list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(0, 0)))
	for(var/bad_layer in list(0, 2, 1.5, "1"))
		var/list/transaction = deep_copy_list(valid)
		transaction["layer"] = bad_layer
		if(workspace.can_transact(transaction))
			Fail("Accepted invalid layer [bad_layer].", __FILE__, __LINE__)
	var/list/transaction = deep_copy_list(valid)
	transaction["dir"] = "3"
	if(workspace.can_transact(transaction))
		Fail("Accepted an unavailable direction.", __FILE__, __LINE__)
	transaction = deep_copy_list(valid)
	transaction["points"] = list(list(0, 0), list(0, 0), list(0, 0), list(0, 0), list(0, 0))
	if(workspace.can_transact(transaction))
		Fail("Accepted more points than canvas pixels.", __FILE__, __LINE__)
	for(var/list/bad_point as anything in list(list("0", 0), list(0.5, 0), list(0), list(0, 0, "forged undo")))
		transaction = deep_copy_list(valid)
		transaction["points"] = list(bad_point)
		if(workspace.can_transact(transaction))
			Fail("Accepted malformed coordinates [json_encode(bad_point)].", __FILE__, __LINE__)
	transaction = deep_copy_list(valid)
	transaction["points"] = list(list(-1, 0), list(0, 0), list(2, 0))
	if(!workspace.can_transact(transaction) || length(transaction["points"]) != 1)
		Fail("A stroke crossing the canvas edge must retain only its in-bounds pixels.", __FILE__, __LINE__)
	transaction = list("type" = "bucket", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "point" = list(-1, 0))
	if(workspace.can_transact(transaction))
		Fail("Accepted an out-of-bounds fill seed.", __FILE__, __LINE__)
	if(workspace.can_transact(list("type" = "flattenLayer", "layer" = 1)))
		Fail("Accepted flattening the bottom layer.", __FILE__, __LINE__)
	if(workspace.can_transact(list("type" = "deleteLayer", "layer" = 1)))
		Fail("Accepted deleting the final layer.", __FILE__, __LINE__)

/datum/unit_test/sprite_editor_history/Run()
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 2, 2, 4, "#123456", SPRITE_EDITOR_COLOR_MODE_RGB, SPRITE_EDITOR_ALLOW_UNDO, SPRITE_EDITOR_TOOL_PENCIL)
	var/datum/sprite_editor_workspace/copied = workspace.copy()
	allocated += copied
	if(copied.backdrop != workspace.backdrop || copied.color_mode != workspace.color_mode || copied.config_flags != workspace.config_flags || copied.tool_flags != workspace.tool_flags)
		Fail("Copy changed workspace configuration.", __FILE__, __LINE__)
	for(var/x in 0 to 1)
		workspace.new_transaction(list("type" = "pencil", "name" = "Forged history", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(x, 0))))
	if(workspace.undo_names[1] != "Pencil")
		Fail("History names must be derived on the server.", __FILE__, __LINE__)
	workspace.undo(2)
	if(length(workspace.undo_stack) || length(workspace.redo_stack) != 2)
		Fail("Undo did not honor its count.", __FILE__, __LINE__)
	workspace.redo(100)
	if(length(workspace.undo_stack) != 2 || length(workspace.redo_stack))
		Fail("Redo did not clamp its count to the available history.", __FILE__, __LINE__)
	var/list/frame = workspace.get_first_layer_pixel_data()
	if(frame[1][1] != "#ffffffff" || frame[1][2] != "#ffffffff")
		Fail("Redo did not restore both painted pixels.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_workspace/Run()
	var/list/bounds = list("2" = list(10, 10, 20, 20))
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ffffff"), bounds)
	if(workspace.can_transact(list("type" = "addLayer")) || workspace.is_valid_color("#ff0000ff") || workspace.is_valid_color("#ffffff80"))
		Fail("Drawing tools must enforce a single layer and opaque sampled shades.", __FILE__, __LINE__)
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(9, 10), list(10, 10))))
	var/list/drawing = workspace.serialize_drawing()
	var/grid = custom_sprite_decode_grid(drawing?["dirs"]?["2"], 1)
	if(!grid || copytext(grid, 331, 332) != "1" || copytext(grid, 330, 331) != "0")
		Fail("The server must clip a stroke to the selected body's bounds.", __FILE__, __LINE__)
	workspace.new_transaction(list("type" = "bucket", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "point" = list(11, 10)))
	var/list/frame = workspace.get_first_layer_pixel_data()
	if(frame[21][21] != "#ffffffff" || frame[22][22] != "#00000000")
		Fail("Bucket fill must obey the same bounds as a pencil.", __FILE__, __LINE__)
	workspace.clear_direction("2")
	if(workspace.serialize_drawing())
		Fail("Clear should remove the direction.", __FILE__, __LINE__)
	workspace.undo()
	if(!workspace.serialize_drawing())
		Fail("Clear must remain undoable.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_workspace_palette/Run()
	var/list/drawing = list("version" = 1, "palette" = list("#123456", "#999999"), "dirs" = list("2" = custom_sprite_encode_grid("1" + repeat_string(1023, "0"))))
	var/list/palette = list()
	for(var/i in 1 to 16)
		palette += rgb(i, 0, 0)
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, drawing, palette, null)
	for(var/i in 1 to 16)
		if(!workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "[palette[i]]ff", "points" = list(list(i, 0)))))
			Fail("A saved drawing must allow all 16 newly available colors.", __FILE__, __LINE__)
	var/list/saved = workspace.serialize_drawing()
	if(saved?["version"] != 2 || length(saved?["palette"]) != 17 || "#999999" in saved?["palette"])
		Fail("Save must retain all used colors and omit unused stored colors.", __FILE__, __LINE__)
	var/datum/sprite_editor_workspace/custom_sprite/reloaded = allocate(/datum/sprite_editor_workspace/custom_sprite, saved, list("#ffffff"), null)
	var/list/frame = reloaded.get_first_layer_pixel_data()
	if(frame[1][1] != "#123456ff" || frame[1][17] != "#100000ff" || !reloaded.is_valid_color("#ffffffff"))
		Fail("Reloading must preserve old pixels and allow the current palette.", __FILE__, __LINE__)
	if(!reloaded.update_palette(list("#abcdef")) || !reloaded.is_valid_color("#abcdefff") || reloaded.is_valid_color("#ffffffff"))
		Fail("Updating available colors must replace unused shades while retaining painted colors.", __FILE__, __LINE__)
	var/datum/sprite_editor_workspace/custom_sprite/history = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#123456"), null)
	history.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#123456ff", "points" = list(list(0, 0))))
	history.undo()
	history.update_palette(list("#abcdef"))
	history.redo()
	var/list/restored = history.serialize_drawing()
	if(!history.is_valid_color("#123456ff") || restored?["palette"]?[1] != "#123456" || custom_sprite_decode_grid(restored?["dirs"]?["2"], 1) != "1" + repeat_string(1023, "0"))
		Fail("Redo after removing a swatch must preserve its original painted color when saving.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_workspace_history_palette_limit/Run()
	var/list/palette = list()
	for(var/i in 1 to 63)
		palette += rgb(i, 0, 0)
	var/grid = "123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_" + repeat_string(961, "0")
	var/list/drawing = list("version" = 2, "palette" = palette, "dirs" = list("2" = custom_sprite_encode_grid(grid, 63)))
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, drawing, palette, null)
	workspace.new_transaction(list("type" = "eraser", "layer" = 1, "dir" = "2", "points" = list(list(0, 0))))
	if(workspace.update_palette(list("#ffffff")))
		Fail("Erasing a color cannot free its palette capacity while undo can restore it.", __FILE__, __LINE__)
	workspace.undo()
	if(workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(31, 31)))))
		Fail("Undo must not allow painting a sixty-fourth color.", __FILE__, __LINE__)
	var/list/saved = workspace.serialize_drawing()
	if(!saved || length(saved["palette"]) != 63 || custom_sprite_decode_grid(saved["dirs"]["2"], 63) != grid)
		Fail("Undo and palette changes must not turn a full drawing into an empty save.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_clear_history/Run()
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ffffff"), null)
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(0, 0), list(31, 31))))
	workspace.undo()
	if(workspace.clear_direction("2") || length(workspace.undo_stack) || length(workspace.redo_stack) != 1)
		Fail("Clearing an empty direction must preserve redo without creating history.", __FILE__, __LINE__)
	workspace.redo()
	workspace.draw_bounds = list("2" = list(10, 10, 20, 20))
	if(!workspace.clear_direction("2") || workspace.serialize_drawing())
		Fail("Clear must erase old pixels outside the current draw bounds.", __FILE__, __LINE__)
	var/list/clear = workspace.undo_stack[length(workspace.undo_stack)]
	if(length(clear["points"]) != 2)
		Fail("Clear must store only the two painted pixels in undo history.", __FILE__, __LINE__)
	workspace.undo()
	var/list/frame = workspace.get_first_layer_pixel_data()
	if(frame[1][1] != "#ffffffff" || frame[32][32] != "#ffffffff" || workspace.is_point_allowed(0, 0, "2"))
		Fail("Undo Clear must restore both pixels while retaining the new drawing bounds.", __FILE__, __LINE__)

/datum/unit_test/sprite_editor_layer_history/Run()
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 2, 2, 4, null, SPRITE_EDITOR_COLOR_MODE_RGBA, ALL, ALL, "#00000000")
	workspace.new_transaction(list("type" = "addLayer", "points" = list("unrelated metadata"), "oldLayer" = list("forged")))
	if(length(workspace.undo_stack[1]) != 2)
		Fail("History must discard fields unrelated to the validated transaction.", __FILE__, __LINE__)
	workspace.new_transaction(list("type" = "pencil", "layer" = 2, "dir" = "8", "color" = "#ffffffff", "points" = list(list(1, 1))))
	workspace.new_transaction(list("type" = "flattenLayer", "layer" = 2))
	if(length(workspace.layers) != 1 || workspace.layers[1]["data"]["8"][2][2] != "#ffffffff")
		Fail("Flatten must blend the actual direction frames.", __FILE__, __LINE__)
	workspace.undo()
	if(length(workspace.layers) != 2 || workspace.layers[1]["data"]["8"][2][2] != "#00000000" || workspace.layers[2]["data"]["8"][2][2] != "#ffffffff")
		Fail("Undo flatten must restore two independent layer records.", __FILE__, __LINE__)
	workspace.new_transaction(list("type" = "deleteLayer", "layer" = 2))
	workspace.undo()
	if(length(workspace.layers) != 2 || workspace.layers[2]["data"]["8"][2][2] != "#ffffffff")
		Fail("Undo delete must restore the entire layer.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_selection_move/Run()
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ff0000", "#00ff00", "#0000ff"), null)
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ff0000ff", "points" = list(list(0, 0))))
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#00ff00ff", "points" = list(list(1, 0))))
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#0000ffff", "points" = list(list(3, 0))))
	var/before = json_encode(workspace.serialize_drawing())
	var/list/move = list("type" = "move", "name" = "Forged", "layer" = 1, "dir" = "2", "rect" = list(0, 0, 2, 0), "offset" = list(1, 0), "points" = list(list(31, 31, "forged", "#ffffffff")))
	if(!workspace.new_transaction(move))
		return Fail("A valid overlapping selection move must be accepted.", __FILE__, __LINE__)
	var/list/frame = workspace.get_first_layer_pixel_data()
	if(frame[1][1] != "#00000000" || frame[1][2] != "#ff0000ff" || frame[1][3] != "#00ff00ff" || frame[1][4] != "#0000ffff" || frame[32][32] != "#00000000")
		Fail("Move must snapshot overlaps, clear its source, ignore transparent source pixels, and discard forged patches.", __FILE__, __LINE__)
	if(length(workspace.undo_stack) != 4 || workspace.undo_names[4] != "Move selection" || length(workspace.undo_stack[4]["points"]) != 3)
		Fail("A move must create one canonical history entry containing only changed pixels.", __FILE__, __LINE__)
	var/after = json_encode(workspace.serialize_drawing())
	workspace.undo()
	if(json_encode(workspace.serialize_drawing()) != before)
		Fail("Undo must restore the complete pre-move drawing.", __FILE__, __LINE__)
	workspace.update_palette(list())
	workspace.redo()
	if(json_encode(workspace.serialize_drawing()) != after || length(workspace.palette) != 3 || workspace.edited_directions["1"])
		Fail("Redo must preserve exact colors and direction isolation after palette refresh.", __FILE__, __LINE__)
	var/datum/sprite_editor_workspace/custom_sprite/reopened = allocate(/datum/sprite_editor_workspace/custom_sprite, workspace.serialize_drawing(), list(), null)
	if(json_encode(reopened.get_first_layer_pixel_data()) != json_encode(frame))
		Fail("Saving and reopening must preserve moved pixels exactly.", __FILE__, __LINE__)
	workspace.new_transaction(list("type" = "move", "layer" = 1, "dir" = "2", "rect" = list(1, 0, 2, 0), "offset" = list(0, 1)))
	if(frame[1][2] != "#00000000" || frame[2][2] != "#ff0000ff" || frame[2][3] != "#00ff00ff")
		Fail("Vertical moves must use the same top-left canvas coordinates as strokes.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_selection_move_validation/Run()
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ffffff"), list("2" = list(10, 10, 20, 20)))
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(10, 10))))
	workspace.undo()
	var/list/valid = list("type" = "move", "layer" = 1, "dir" = "2", "rect" = list(10, 10, 11, 11), "offset" = list(1, 0))
	var/list/invalid = list(
		list("rect" = list(10, 10, 11)),
		list("rect" = list(10, 10, 9, 11)),
		list("rect" = list(10, 10, 32, 11)),
		list("rect" = list(10, 10, 11.5, 11)),
		list("rect" = list("10", 10, 11, 11)),
		list("rect" = list(-1, 10, 11, 11)),
		list("offset" = list(10, 0)),
		list("offset" = list(-11, 0)),
		list("offset" = list(0.5, 0)),
		list("offset" = list("1", 0)),
		list("offset" = list(1, 0, 0)),
		list("offset" = list(1000000, 0)),
		list("dir" = "3"),
		list("dir" = 2),
		list("layer" = 1.5),
		list("layer" = 2),
	)
	for(var/list/replacement as anything in invalid)
		var/list/transaction = deep_copy_list(valid)
		for(var/key in replacement)
			transaction[key] = replacement[key]
		if(workspace.new_transaction(transaction))
			Fail("Rejected move metadata must not enter history: [json_encode(replacement)].", __FILE__, __LINE__)
	if(workspace.new_transaction(deep_copy_list(valid)) || length(workspace.undo_stack) || length(workspace.redo_stack) != 1)
		Fail("Empty moves and malformed moves must preserve redo without recording history.", __FILE__, __LINE__)
	workspace.redo()
	valid["offset"] = list(0, 0)
	if(workspace.new_transaction(deep_copy_list(valid)) || length(workspace.undo_stack) != 1)
		Fail("Zero displacement must not create a transaction.", __FILE__, __LINE__)
	if(!(workspace.tool_flags & 16))
		Fail("Custom workspaces must advertise the Select tool.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_selection_shaded_margin/Run()
	var/list/rows = list()
	for(var/y in 0 to 31)
		rows += y == 10 ? "[repeat_string(10, "0")]111[repeat_string(19, "0")]" : repeat_string(32, "0")
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ff0000", "#0000ff"), list("2" = list(10, 10, 20, 20)), list("2" = rows))
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ff0000ff", "points" = list(list(10, 10))))
	var/list/frame = workspace.get_first_layer_pixel_data()
	frame[10][10] = "#0000ffff"
	var/before = json_encode(frame)
	var/list/move = list("type" = "move", "layer" = 1, "dir" = "2", "rect" = list(9, 9, 10, 10), "offset" = list(1, 0))
	if(!workspace.new_transaction(deep_copy_list(move)) || frame[11][11] != "#00000000" || frame[11][12] != "#ff0000ff" || frame[10][10] != "#0000ffff")
		return Fail("A selection starting in shaded margins must move allowed paint and leave hidden pixels untouched.", __FILE__, __LINE__)
	var/after = json_encode(frame)
	workspace.undo()
	if(json_encode(frame) != before)
		Fail("Undo must restore the exact frame, including hidden pixels.", __FILE__, __LINE__)
	workspace.redo()
	if(json_encode(frame) != after)
		Fail("Redo must restore the shaded-margin move exactly.", __FILE__, __LINE__)
	move["rect"] = list(9, 9, 11, 10)
	for(var/list/offset as anything in list(list(-2, 0), list(2, 0), list(1, 1), list(-10, 0), list(21, 0)))
		move["offset"] = offset
		if(workspace.new_transaction(deep_copy_list(move)) || json_encode(frame) != after || length(workspace.undo_stack) != 2)
			Fail("Selection margins must not permit paint outside bounds or masks, or a box outside the canvas.", __FILE__, __LINE__)

/datum/unit_test/sprite_editor_selection_move/Run()
	var/obj/item/canvas/canvas = allocate(/obj/item/canvas)
	if(!(canvas.workspace.tool_flags & 16) || (canvas.workspace.tool_flags & SPRITE_EDITOR_TOOL_ERASER) || canvas.workspace.config_flags)
		Fail("Canvas must enable Select while preserving its other tool and history restrictions.", __FILE__, __LINE__)
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 4, 4, 4, null, SPRITE_EDITOR_COLOR_MODE_RGBA, ALL, ALL, "#00000000")
	workspace.new_transaction(list("type" = "addLayer"))
	workspace.new_transaction(list("type" = "pencil", "layer" = 2, "dir" = "8", "color" = "#ff000080", "points" = list(list(0, 0))))
	workspace.new_transaction(list("type" = "pencil", "layer" = 2, "dir" = "8", "color" = "#00ff00ff", "points" = list(list(1, 0))))
	var/before = json_encode(workspace.layers)
	if(!workspace.new_transaction(list("type" = "move", "layer" = 2, "dir" = "8", "rect" = list(0, 0, 0, 0), "offset" = list(1, 0))))
		return Fail("Generic painting workspaces must accept selection movement.", __FILE__, __LINE__)
	if(workspace.layers[2]["data"]["8"][1][2] != "#ff000080" || workspace.layers[2]["data"]["8"][1][1] != "#00000000" || workspace.layers[1]["data"]["8"][1][2] != "#00000000" || workspace.layers[2]["data"]["2"][1][2] != "#00000000")
		Fail("Move must replace translucent pixels exactly, without blending or changing other layers/directions.", __FILE__, __LINE__)
	workspace.undo()
	if(json_encode(workspace.layers) != before)
		Fail("Undo must restore overwritten destination pixels and the source alpha.", __FILE__, __LINE__)
	workspace.tool_flags = SPRITE_EDITOR_TOOL_PENCIL
	if(workspace.new_transaction(list("type" = "move", "layer" = 2, "dir" = "8", "rect" = list(0, 0, 0, 0), "offset" = list(1, 0))) || length(workspace.redo_stack) != 1)
		Fail("Workspaces without the Select flag must reject moves without losing redo.", __FILE__, __LINE__)
	workspace.tool_flags = ALL
	var/list/frame = workspace.layers[2]["data"]["8"]
	frame[3][1] = "#000000"
	frame[3][2] = "#12345600"
	frame[3][3] = "#ffffffff"
	frame[3][4] = "#0000ffff"
	if(!workspace.new_transaction(list("type" = "move", "layer" = 2, "dir" = "8", "rect" = list(0, 2, 1, 2), "offset" = list(2, 0))) || frame[3][3] != "#000000" || frame[3][4] != "#0000ffff")
		Fail("Six-digit RGB black is opaque; colored zero-alpha pixels must not replace the destination.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_limb_mask/Run()
	var/list/rows = list("1011[repeat_string(28, "0")]")
	for(var/y in 2 to 32)
		rows += repeat_string(32, "0")
	var/list/mask = list("2" = rows)
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ff0000", "#0000ff"), null, mask)
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ff0000ff", "points" = list(list(0, 0), list(1, 0))))
	var/list/frame = workspace.get_first_layer_pixel_data()
	if(frame[1][1] != "#ff0000ff" || frame[1][2] != "#00000000")
		Fail("Pencil must clip points in silhouette holes.", __FILE__, __LINE__)
	// Old pixels can remain outside a changed species' mask; moving a selection must leave them alone.
	frame[1][2] = "#0000ffff"
	workspace.new_transaction(list("type" = "eraser", "layer" = 1, "dir" = "2", "points" = list(list(1, 0))))
	if(frame[1][2] != "#0000ffff")
		Fail("Ordinary erasing must respect the limb mask.", __FILE__, __LINE__)
	var/list/move = list("type" = "move", "layer" = 1, "dir" = "2", "rect" = list(0, 0, 1, 0), "offset" = list(1, 0))
	if(workspace.new_transaction(deep_copy_list(move)))
		Fail("Selection must reject moving painted pixels off the limb.", __FILE__, __LINE__)
	move["offset"] = list(2, 0)
	if(!workspace.new_transaction(move) || frame[1][1] != "#00000000" || frame[1][2] != "#0000ffff" || frame[1][3] != "#ff0000ff")
		Fail("Selection must cross holes without moving hidden pixels.", __FILE__, __LINE__)
	workspace.undo()
	if(frame[1][1] != "#ff0000ff" || frame[1][2] != "#0000ffff" || frame[1][3] != "#00000000")
		Fail("Undo must restore mask-aware moves exactly.", __FILE__, __LINE__)
	workspace.clear_direction("2")
	if(workspace.edited_directions["2"] || workspace.draw_mask != mask)
		Fail("Clear must remove stale out-of-mask pixels and restore the mask.", __FILE__, __LINE__)
	workspace.new_transaction(list("type" = "bucket", "layer" = 1, "dir" = "2", "color" = "#ff0000ff", "point" = list(0, 0)))
	if(frame[1][1] != "#ff0000ff" || frame[1][3] != "#00000000" || frame[1][4] != "#00000000")
		Fail("Fill must stop at silhouette holes instead of reaching disconnected pixels through the backdrop.", __FILE__, __LINE__)
	for(var/y in 0 to 31)
		for(var/x in 0 to 31)
			if(!workspace.is_point_allowed(x, y, "2") && frame[y + 1][x + 1] != "#00000000")
				Fail("Fill must never paint outside the limb silhouette.", __FILE__, __LINE__)
	if(workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "1", "color" = "#ff0000ff", "points" = list(list(0, 0)))))
		Fail("An absent direction mask must reject paint.", __FILE__, __LINE__)

#endif
