#if defined(UNIT_TESTS) || defined(SPACEMAN_DMM)

/datum/unit_test/sprite_editor_validation/Run()
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 2, 2, 4)
	var/list/valid = list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(0, 0)))
	for(var/bad_layer in list(0, 2, 1.5, "1"))
		var/list/transaction = deep_copy_list(valid)
		transaction["layer"] = bad_layer
		if(workspace.can_transact(transaction))
			Fail("Accepted invalid layer [bad_layer].", __FILE__, __LINE__)
	var/list/transaction = deep_copy_list(valid)
	transaction["dir"] = "3"
	if(workspace.can_transact(transaction))
		Fail("Accepted an unavailable direction.", __FILE__, __LINE__)
	transaction = deep_copy_list(valid)
	transaction["points"] = list(list(0, 0), list(0, 0), list(0, 0), list(0, 0), list(0, 0))
	if(workspace.can_transact(transaction))
		Fail("Accepted more points than canvas pixels.", __FILE__, __LINE__)
	for(var/list/bad_point as anything in list(list("0", 0), list(0.5, 0), list(0), list(0, 0, "forged undo")))
		transaction = deep_copy_list(valid)
		transaction["points"] = list(bad_point)
		if(workspace.can_transact(transaction))
			Fail("Accepted malformed coordinates [json_encode(bad_point)].", __FILE__, __LINE__)
	transaction = deep_copy_list(valid)
	transaction["points"] = list(list(-1, 0), list(0, 0), list(2, 0))
	if(!workspace.can_transact(transaction) || length(transaction["points"]) != 1)
		Fail("A stroke crossing the canvas edge must retain only its in-bounds pixels.", __FILE__, __LINE__)
	transaction = list("type" = "bucket", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "point" = list(-1, 0))
	if(workspace.can_transact(transaction))
		Fail("Accepted an out-of-bounds fill seed.", __FILE__, __LINE__)
	if(workspace.can_transact(list("type" = "flattenLayer", "layer" = 1)))
		Fail("Accepted flattening the bottom layer.", __FILE__, __LINE__)
	if(workspace.can_transact(list("type" = "deleteLayer", "layer" = 1)))
		Fail("Accepted deleting the final layer.", __FILE__, __LINE__)

/datum/unit_test/sprite_editor_history/Run()
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 2, 2, 4, "#123456", SPRITE_EDITOR_COLOR_MODE_RGB, SPRITE_EDITOR_ALLOW_UNDO, SPRITE_EDITOR_TOOL_PENCIL)
	var/datum/sprite_editor_workspace/copied = workspace.copy()
	allocated += copied
	if(copied.backdrop != workspace.backdrop || copied.color_mode != workspace.color_mode || copied.config_flags != workspace.config_flags || copied.tool_flags != workspace.tool_flags)
		Fail("Copy changed workspace configuration.", __FILE__, __LINE__)
	for(var/x in 0 to 1)
		workspace.new_transaction(list("type" = "pencil", "name" = "Forged history", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(x, 0))))
	if(workspace.undo_names[1] != "Pencil")
		Fail("History names must be derived on the server.", __FILE__, __LINE__)
	workspace.undo(2)
	if(length(workspace.undo_stack) || length(workspace.redo_stack) != 2)
		Fail("Undo did not honor its count.", __FILE__, __LINE__)
	workspace.redo(100)
	if(length(workspace.undo_stack) != 2 || length(workspace.redo_stack))
		Fail("Redo did not clamp its count to the available history.", __FILE__, __LINE__)
	var/list/frame = workspace.get_first_layer_pixel_data()
	if(frame[1][1] != "#ffffffff" || frame[1][2] != "#ffffffff")
		Fail("Redo did not restore both painted pixels.", __FILE__, __LINE__)

/datum/unit_test/custom_sprite_workspace/Run()
	var/list/bounds = list("2" = list(10, 10, 20, 20))
	var/datum/sprite_editor_workspace/custom_sprite/workspace = allocate(/datum/sprite_editor_workspace/custom_sprite, null, list("#ffffff"), bounds)
	if(workspace.can_transact(list("type" = "addLayer")) || workspace.is_valid_color("#ff0000ff") || workspace.is_valid_color("#ffffff80"))
		Fail("Drawing tools must enforce a single layer and opaque sampled shades.", __FILE__, __LINE__)
	workspace.new_transaction(list("type" = "pencil", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "points" = list(list(9, 10), list(10, 10))))
	var/list/drawing = workspace.serialize_drawing()
	var/grid = custom_sprite_decode_grid(drawing?["dirs"]?["2"], 1)
	if(!grid || copytext(grid, 331, 332) != "1" || copytext(grid, 330, 331) != "0")
		Fail("The server must clip a stroke to the selected body's bounds.", __FILE__, __LINE__)
	workspace.new_transaction(list("type" = "bucket", "layer" = 1, "dir" = "2", "color" = "#ffffffff", "point" = list(11, 10)))
	var/list/frame = workspace.get_first_layer_pixel_data()
	if(frame[21][21] != "#ffffffff" || frame[22][22] != "#00000000")
		Fail("Bucket fill must obey the same bounds as a pencil.", __FILE__, __LINE__)
	workspace.clear_direction("2")
	if(workspace.serialize_drawing())
		Fail("Clear should remove the direction.", __FILE__, __LINE__)
	workspace.undo()
	if(!workspace.serialize_drawing())
		Fail("Clear must remain undoable.", __FILE__, __LINE__)

/datum/unit_test/sprite_editor_layer_history/Run()
	var/datum/sprite_editor_workspace/workspace = allocate(/datum/sprite_editor_workspace, 2, 2, 4, null, SPRITE_EDITOR_COLOR_MODE_RGBA, ALL, ALL, "#00000000")
	workspace.new_transaction(list("type" = "addLayer", "points" = list("unrelated metadata"), "oldLayer" = list("forged")))
	if(length(workspace.undo_stack[1]) != 2)
		Fail("History must discard fields unrelated to the validated transaction.", __FILE__, __LINE__)
	workspace.new_transaction(list("type" = "pencil", "layer" = 2, "dir" = "8", "color" = "#ffffffff", "points" = list(list(1, 1))))
	workspace.new_transaction(list("type" = "flattenLayer", "layer" = 2))
	if(length(workspace.layers) != 1 || workspace.layers[1]["data"]["8"][2][2] != "#ffffffff")
		Fail("Flatten must blend the actual direction frames.", __FILE__, __LINE__)
	workspace.undo()
	if(length(workspace.layers) != 2 || workspace.layers[1]["data"]["8"][2][2] != "#00000000" || workspace.layers[2]["data"]["8"][2][2] != "#ffffffff")
		Fail("Undo flatten must restore two independent layer records.", __FILE__, __LINE__)
	workspace.new_transaction(list("type" = "deleteLayer", "layer" = 2))
	workspace.undo()
	if(length(workspace.layers) != 2 || workspace.layers[2]["data"]["8"][2][2] != "#ffffffff")
		Fail("Undo delete must restore the entire layer.", __FILE__, __LINE__)

#endif
