// Produce an offline, read-only review surface from an immutable package.
import fs from 'node:fs';
import path from 'node:path';
import {readPackage} from './data-contract.js';
const [directory, output] = process.argv.slice(2);
if (!directory || !output) throw new Error('Usage: explore.js <package-directory> <new-output.html>');
if (fs.existsSync(output)) throw new Error('Review output already exists');
const {manifest,records} = await readPackage(directory);
const assets = path.relative(path.dirname(path.resolve(output)),path.resolve(directory,'icons')).replaceAll('\\','/');
const payload = JSON.stringify({records,assets,commit:manifest.source.commit,dirty:manifest.provenance?.dirty ?? true}).replaceAll('<','\\u003c');
fs.writeFileSync(output, `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Meridian · Game Data Review</title>
<style>:root{color-scheme:dark;font:15px/1.5 system-ui;background:#141311;color:#ebe7df}body{max-width:1400px;margin:auto;padding:24px}h1{margin:0;color:#62d7de}p{margin:8px 0;color:#b8b1a5}header{border-bottom:1px solid #4e4941;padding-bottom:18px}form{display:flex;gap:12px;flex-wrap:wrap;margin:20px 0}input,select,button{font:inherit;background:#201e1a;border:1px solid #696257;border-radius:4px;padding:8px;color:inherit}input{flex:1;min-width:220px}button{cursor:pointer}button:disabled{opacity:.4}table{width:100%;border-collapse:collapse}th{text-align:left;position:sticky;top:0;background:#292620}td,th{padding:9px 12px;border-bottom:1px solid #38352f;vertical-align:top}td:first-child{width:29%}td img{width:48px;height:48px;object-fit:contain;image-rendering:pixelated;float:left;margin-right:12px}summary{cursor:pointer;color:#62d7de}dl{display:grid;grid-template-columns:minmax(90px,1fr) 3fr;gap:6px;font-size:13px}dt{color:#b8b1a5}dd{margin:0;overflow-wrap:anywhere}code{overflow-wrap:anywhere}nav{display:flex;align-items:center;gap:15px;margin:18px 0}a{color:#62d7de}small{display:block;color:#b8b1a5}@media(max-width:650px){body{padding:12px}td,th{padding:7px}td:first-child{width:40%}dl{display:block}}</style>
<header><h1>Game Data Review</h1><p>Source definitions for editors. Initial appearances, base costs and defaults can differ from the live game. Variable recipe fields are marked; this is not server policy.</p><small id="build"></small></header>
<form><label>Dataset <select id="kind"></select></label><input id="query" type="search" aria-label="Filter records" placeholder="Filter names, descriptions, ingredients or source identities"><button type="reset">Clear</button></form><p id="count" aria-live="polite"></p><nav><button id="prev">Previous</button><span id="page"></span><button id="next">Next</button></nav><table><thead><tr><th scope="col">Entry</th><th scope="col">Source Facts</th></tr></thead><tbody id="rows"></tbody></table>
<script type="application/json" id="data">${payload}</script><script>
const data=JSON.parse(document.querySelector('#data').textContent), names=new Map(data.records.map(r=>[r.id,r.fields.name||r.fields.title||r.fields.display_name||r.id.split('/').pop()]));
const labels={entity:'Objects and Items',research_node:'Research',design:'Fabrication',reagent:'Reagents',reaction:'Chemical Reactions',crafting_recipe:'Crafting',supply_pack:'Cargo',job:'Jobs',outfit:'Outfits',vending:'Vending',species:'Species',projectile:'Projectiles',material:'Materials',surgery:'Surgery',armor:'Armor',scenario:'Tested Scenarios',dictionary:'Dictionaries'};
const el=id=>document.getElementById(id), make=(tag,text)=>{let e=document.createElement(tag);e.textContent=text;return e};let page=0,filtered=[];
for(const [value,label] of Object.entries(labels)){let o=make('option',label);o.value=value;el('kind').append(o)}el('kind').value='reagent';
el('build').textContent=(data.dirty?'Development snapshot · ':'Source snapshot · ')+data.commit;
function format(v){if(v===null)return 'Unspecified';if(Array.isArray(v))return v.map(p=>format(p.key)+(p.value===null?'':' × '+format(p.value))).join(', ')||'None';return names.get(v)||String(v)}
const summaries={entity:['description','weight_class','force','tool_behavior'],research_node:['description','research_costs','prerequisite_nodes','unlocked_designs'],design:['desc','materials','reagents_list','construction_time','unlocked_by'],reagent:['description','ph','metabolization_rate','overdose_threshold'],reaction:['required_reagents','results','required_catalysts','required_temp','dynamic_fields'],crafting_recipe:['reqs','result','result_amount','time','tool_behaviors'],supply_pack:['desc','cost','contains'],job:['description','exp_requirements','minimal_player_age','paycheck']};
const title=s=>s.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
function fieldsView(record,fields){let dl=document.createElement('dl'),dynamic=new Set((record.fields.dynamic_fields||[]).map(p=>p.key));for(const key of fields){if(!(key in record.fields))continue;dl.append(make('dt',title(key)));let v=dynamic.has(key)?'Variable — determined at runtime':format(record.fields[key]);if(['construction_time','time'].includes(key)&&typeof record.fields[key]==='number')v=(record.fields[key]/10)+' seconds';if(key==='required_temp'&&typeof record.fields[key]==='number')v+=' K';if(key==='cost')v+=' base credits';dl.append(make('dd',v))}return dl}
function draw(){let start=page*50;el('rows').replaceChildren();for(const r of filtered.slice(start,start+50)){let tr=document.createElement('tr'),name=document.createElement('td'),facts=document.createElement('td');if(r.fields.icon_file){let im=document.createElement('img');im.src=data.assets+'/'+r.fields.icon_file;im.alt='';im.loading='lazy';name.append(im)}name.append(make('strong',names.get(r.id)));let detail=document.createElement('details');detail.append(make('summary','All source fields'),make('code',r.id),fieldsView(r,Object.keys(r.fields)));facts.append(fieldsView(r,summaries[r.kind]||Object.keys(r.fields).slice(0,6)),detail);tr.append(name,facts);el('rows').append(tr)}el('count').textContent=filtered.length.toLocaleString()+' matching records';el('page').textContent='Page '+(page+1)+' of '+Math.max(1,Math.ceil(filtered.length/50));el('prev').disabled=!page;el('next').disabled=start+50>=filtered.length}
function search(){let q=el('query').value.toLocaleLowerCase(),kind=el('kind').value;filtered=data.records.filter(r=>r.kind===kind&&(!q||(r.id+' '+Object.values(r.fields).map(format).join(' ')).toLocaleLowerCase().includes(q)));page=0;draw()}
el('kind').addEventListener('change',search);let timer;el('query').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(search,150)});document.querySelector('form').addEventListener('submit',e=>e.preventDefault());document.querySelector('form').addEventListener('reset',()=>{setTimeout(search,0)});el('prev').onclick=()=>{page--;draw()};el('next').onclick=()=>{page++;draw()};search();
</script></html>`);
console.log(JSON.stringify({output,records:records.length}));
