// Generated by tools/cyborg_customization/build_assets.py; do not edit.
/proc/cyborg_occlusion_resources()
	var/static/list/resources = list(
		"modular_nova/modules/borgs/icons/widerobot_eng.dmi" = 'modular_aphelion/modules/cyborg_customization/icons/occlusion_generated/widerobot_eng.dmi',
		"modular_nova/modules/borgs/icons/widerobot_jani.dmi" = 'modular_aphelion/modules/cyborg_customization/icons/occlusion_generated/widerobot_jani.dmi',
		"modular_nova/modules/borgs/icons/widerobot_mine.dmi" = 'modular_aphelion/modules/cyborg_customization/icons/occlusion_generated/widerobot_mine.dmi',
		"modular_nova/modules/borgs/icons/widerobot_pk.dmi" = 'modular_aphelion/modules/cyborg_customization/icons/occlusion_generated/widerobot_pk.dmi',
		"modular_nova/modules/borgs/icons/widerobot_sec.dmi" = 'modular_aphelion/modules/cyborg_customization/icons/occlusion_generated/widerobot_sec.dmi',
		"modular_nova/modules/borgs/icons/widerobot_serv.dmi" = 'modular_aphelion/modules/cyborg_customization/icons/occlusion_generated/widerobot_serv.dmi',
		"modular_nova/modules/borgs/icons/widerobots_cargo.dmi" = 'modular_aphelion/modules/cyborg_customization/icons/occlusion_generated/widerobots_cargo.dmi',
	)
	return resources
