// Regression coverage for injury-derived pain, treatment, and independent symptom timing.
/datum/unit_test/medical_pain

// Exercise the medical paths without yielding to natural mob processing.
/datum/unit_test/medical_pain/Run()
	test_injury_healing()
	test_organs()
	test_fracture()
	test_analgesia()
	test_stage_timing()
	test_lifecycle()
	test_synthetic_bodies()

// Stored limb damage heals directly; oxygen and exhaustion must not create pain.
/datum/unit_test/medical_pain/proc/test_injury_healing()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	TEST_ASSERT_NOTNULL(patient.medical_pain, "Humans must initialize their medical pain state.")
	var/obj/item/bodypart/arm = patient.get_bodypart(BODY_ZONE_R_ARM)
	arm.receive_damage(brute = 20, burn = 10, wound_bonus = CANT_WOUND)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 32, "Stored brute and burns must contribute without armor being applied again.")
	arm.heal_damage(20, 10)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 0, "Direct limb healing must remove its pain.")
	patient.adjust_oxy_loss(50)
	patient.adjust_stamina_loss(50)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 0, "Oxygen damage and exhaustion must not become injury pain.")
	TEST_ASSERT(patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "Non-pain damage must retain movement impairment.")
	ADD_TRAIT(patient, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	patient.medical_pain.recalculate()
	TEST_ASSERT(patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "Pain immunity must not erase oxygen or stamina impairment.")

// Organ-only damage must be sampled independently of health and have an aggregate cap.
/datum/unit_test/medical_pain/proc/test_organs()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/organ/liver = patient.get_organ_slot(ORGAN_SLOT_LIVER)
	patient.set_organ_loss(ORGAN_SLOT_LIVER, liver.high_threshold)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 20, "A damaged liver must hurt without limb injury.")
	patient.set_organ_loss(ORGAN_SLOT_LIVER, 0)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 0, "Organ repair must remove its contribution.")
	for(var/organ_slot in list(ORGAN_SLOT_LIVER, ORGAN_SLOT_LUNGS, ORGAN_SLOT_STOMACH, ORGAN_SLOT_APPENDIX))
		var/obj/item/organ/damaged_organ = patient.get_organ_slot(organ_slot)
		patient.set_organ_loss(organ_slot, damaged_organ.high_threshold)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 60, "Multiple organ injuries must respect the aggregate cap.")

// A fracture persists after brute healing and responds to actual limb dressing state.
/datum/unit_test/medical_pain/proc/test_fracture()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/bodypart/arm = patient.get_bodypart(BODY_ZONE_R_ARM)
	var/datum/wound/blunt/bone/severe/fracture = new
	TEST_ASSERT(fracture.apply_wound(arm, silent = TRUE), "The fracture fixture must attach to its limb.")
	arm.heal_damage(INFINITY, INFINITY)
	patient.reagents.clear_reagents()
	patient.medical_pain.recalculate()
	var/untreated_pain = patient.medical_pain.raw_pain
	TEST_ASSERT(untreated_pain > 0, "An untreated fracture must hurt with healed brute damage.")
	var/obj/item/stack/medical/wrap/gauze/dressing = allocate(/obj/item/stack/medical/wrap/gauze)
	TEST_ASSERT(arm.apply_item(dressing, LIMB_ITEM_GAUZE), "The dressing fixture must attach.")
	patient.medical_pain.recalculate()
	TEST_ASSERT(patient.medical_pain.raw_pain < untreated_pain, "Splinting must reduce fracture pain without requiring new damage.")
	TEST_ASSERT(fracture in arm.wounds, "Symptom relief must not repair a fracture.")
	dressing.forceMove(run_loc_floor_bottom_left)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, untreated_pain, "Removing a splint must restore untreated fracture pain.")
	qdel(fracture)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 0, "Removing the repaired wound must clear the persistent surcharge.")

// Relief follows active metabolism, uses the strongest source, and disappears on purge.
/datum/unit_test/medical_pain/proc/test_analgesia()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	patient.reagents.add_reagent(/datum/reagent/medicine/granibitaluri, 10)
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 0, "An inactive reagent must not provide bloodstream relief.")
	var/datum/reagent/mild = patient.reagents.has_reagent(/datum/reagent/medicine/granibitaluri)
	mild.compute_metabolization(patient, SSMOBS_DT)
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 25, "Active mild medicine must provide finite relief.")
	TEST_ASSERT(!patient.has_surgical_analgesia(), "Mild medicine must not provide surgical anesthesia.")
	patient.reagents.add_reagent(/datum/reagent/medicine/morphine, 10)
	var/datum/reagent/strong = patient.reagents.has_reagent(/datum/reagent/medicine/morphine)
	strong.compute_metabolization(patient, SSMOBS_DT)
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 80, "Mixed analgesics must use the strongest source, not add strengths.")
	TEST_ASSERT(patient.has_surgical_analgesia(), "Morphine must retain surgical analgesia.")
	patient.reagents.remove_reagent(/datum/reagent/medicine/morphine, INFINITY)
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 25, "Purging the strongest source must expose remaining mild relief.")
	patient.reagents.end_metabolization(patient, keep_liverless = FALSE)
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 0, "Stopped metabolism must not retain analgesia.")
	patient.reagents.clear_reagents()
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 0, "Purging all drugs must leave no stale relief.")

// Extra reads cannot accelerate stages, and recovery uses a separate threshold.
/datum/unit_test/medical_pain/proc/test_stage_timing()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	patient.adjust_tox_loss(160)
	var/datum/medical_pain/pain_state = patient.medical_pain
	var/simulation_time = world.time + 2 SECONDS
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time)
	TEST_ASSERT_EQUAL(pain_state.stage, 1, "An injury must escalate by only one stage per interval.")
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time)
	TEST_ASSERT_EQUAL(pain_state.stage, 1, "Repeated updates in the same interval must not escalate symptoms.")
	pain_state.recalculate(current_time = simulation_time + 2 SECONDS)
	TEST_ASSERT_EQUAL(pain_state.stage, 1, "A diagnostic refresh must not advance the stage.")
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time + 2 SECONDS)
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time + 4 SECONDS)
	TEST_ASSERT_EQUAL(pain_state.stage, 3, "Sustained forty-percent pain must reach stage three.")
	patient.adjust_tox_loss(-12)
	pain_state.recalculate()
	TEST_ASSERT_EQUAL(pain_state.stage, 3, "Thirty-seven-percent pain must stay within stage-three recovery hysteresis.")
	patient.adjust_tox_loss(-10)
	pain_state.recalculate()
	TEST_ASSERT_EQUAL(pain_state.stage, 2, "Pain below thirty-five percent must recover promptly to stage two.")
	ADD_TRAIT(patient, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	pain_state.recalculate()
	TEST_ASSERT(pain_state.raw_pain > 0, "Pain immunity must not heal the underlying injury.")
	TEST_ASSERT_EQUAL(pain_state.effective_pain, 0, "Explicit pain immunity must suppress effective pain.")
	TEST_ASSERT_EQUAL(pain_state.stage, 0, "Complete relief must clear symptom stage immediately.")

// Stasis, death and healing clear owned symptoms while preserving unrelated modifiers.
/datum/unit_test/medical_pain/proc/test_lifecycle()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/bodypart/arm = patient.get_bodypart(BODY_ZONE_R_ARM)
	arm.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	var/datum/medical_pain/pain_state = patient.medical_pain
	pain_state.recalculate(advance_stage = TRUE, current_time = world.time + 2 SECONDS)
	TEST_ASSERT(patient.has_status_effect(/datum/status_effect/medical_pain), "Pain symptoms must have a patient status.")
	patient.add_or_update_variable_movespeed_modifier(/datum/movespeed_modifier/admin_varedit, multiplicative_slowdown = 0.7)
	ADD_TRAIT(patient, TRAIT_STASIS, TRAIT_SOURCE_UNIT_TESTS)
	TEST_ASSERT_EQUAL(pain_state.stage, 0, "Entering stasis must clear symptoms immediately.")
	TEST_ASSERT(!patient.has_status_effect(/datum/status_effect/medical_pain), "Stasis must remove the pain alert.")
	TEST_ASSERT(patient.has_movespeed_modifier(/datum/movespeed_modifier/admin_varedit), "Pain cleanup must preserve unrelated movement modifiers.")
	REMOVE_TRAIT(patient, TRAIT_STASIS, TRAIT_SOURCE_UNIT_TESTS)
	TEST_ASSERT_EQUAL(pain_state.effective_pain, 40, "Leaving stasis must restore untreated injury pain.")
	pain_state.recalculate(advance_stage = TRUE, current_time = world.time + 4 SECONDS)
	patient.death()
	TEST_ASSERT_EQUAL(pain_state.stage, 0, "Death must clear pain symptoms immediately.")
	TEST_ASSERT(!patient.has_status_effect(/datum/status_effect/medical_pain), "Death must remove the pain alert.")
	patient.revive()
	TEST_ASSERT_EQUAL(pain_state.effective_pain, 40, "Revival without healing must resample the surviving injury.")
	pain_state.recalculate(advance_stage = TRUE, current_time = world.time + 6 SECONDS)
	patient.fully_heal(ADMIN_HEAL_ALL)
	TEST_ASSERT_EQUAL(pain_state.raw_pain, 0, "Full healing must resample the repaired body.")
	TEST_ASSERT_EQUAL(pain_state.stage, 0, "Full healing must clear pain symptoms.")

// Prosthetic injury is painless and synthetic species retain their original damage slowdown.
/datum/unit_test/medical_pain/proc/test_synthetic_bodies()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/bodypart/old_arm = patient.get_bodypart(BODY_ZONE_R_ARM)
	old_arm.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	patient.medical_pain.recalculate(advance_stage = TRUE, current_time = world.time + 2 SECONDS)
	var/obj/item/bodypart/arm/right/robot/prosthesis = allocate(/obj/item/bodypart/arm/right/robot)
	TEST_ASSERT(prosthesis.replace_limb(patient), "The prosthetic fixture must replace the injured arm.")
	qdel(old_arm)
	prosthesis.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 0, "Damaged machinery must not cause organic pain.")
	TEST_ASSERT_EQUAL(patient.medical_pain.stage, 0, "Replacing the painful limb must clear symptoms.")
	patient.set_species(/datum/species/android)
	TEST_ASSERT(!patient.uses_medical_pain(), "Androids must opt out of organic pain.")
	patient.adjust_brute_loss(60)
	patient.medical_pain.recalculate(advance_stage = TRUE, current_time = world.time + 4 SECONDS)
	TEST_ASSERT_EQUAL(patient.medical_pain.stage, 0, "Synthetic damage must not escalate pain symptoms.")
	TEST_ASSERT(patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "Synthetic bodies must retain legacy damage impairment.")
