// Regression coverage for injury-derived pain, treatment, and independent symptom timing.
/datum/unit_test/medical_pain

// Exercise the medical paths without yielding to natural mob processing.
/datum/unit_test/medical_pain/Run()
	test_injury_healing()
	test_organs()
	test_fracture()
	test_analgesia()
	test_stage_timing()
	test_lifecycle()
	test_synthetic_bodies()
	test_crit_deferral()
	test_treatment_control()
	test_physiological_guards()
	test_organ_guards()
	test_unrelated_preservation()
	test_overflow_shares()
	test_overflow_guards()
	test_high_pain_ramp()
	test_hardcrit_floors()

// Stored limb damage heals directly; oxygen and exhaustion must not create pain.
/datum/unit_test/medical_pain/proc/test_injury_healing()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	TEST_ASSERT_NOTNULL(patient.medical_pain, "Humans must initialize their medical pain state.")
	var/obj/item/bodypart/arm = patient.get_bodypart(BODY_ZONE_R_ARM)
	arm.receive_damage(brute = 20, burn = 10, wound_bonus = CANT_WOUND)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 39, "Scaled brute and burns must contribute without armor being applied again.")
	arm.heal_damage(20, 10)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 0, "Direct limb healing must remove its pain.")
	patient.adjust_oxy_loss(50)
	patient.adjust_stamina_loss(50)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 0, "Oxygen damage and exhaustion must not become injury pain.")
	TEST_ASSERT(patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "Non-pain damage must retain movement impairment.")
	ADD_TRAIT(patient, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	patient.medical_pain.recalculate()
	TEST_ASSERT(patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "Pain immunity must not erase oxygen or stamina impairment.")

// Organ-only damage must be sampled independently of health and have an aggregate cap.
/datum/unit_test/medical_pain/proc/test_organs()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/organ/liver = patient.get_organ_slot(ORGAN_SLOT_LIVER)
	patient.set_organ_loss(ORGAN_SLOT_LIVER, liver.high_threshold)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 20, "A damaged liver must hurt without limb injury.")
	patient.set_organ_loss(ORGAN_SLOT_LIVER, 0)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 0, "Organ repair must remove its contribution.")
	for(var/organ_slot in list(ORGAN_SLOT_LIVER, ORGAN_SLOT_LUNGS, ORGAN_SLOT_STOMACH, ORGAN_SLOT_APPENDIX))
		var/obj/item/organ/damaged_organ = patient.get_organ_slot(organ_slot)
		patient.set_organ_loss(organ_slot, damaged_organ.high_threshold)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 60, "Multiple organ injuries must respect the aggregate cap.")

// A fracture persists after brute healing and responds to actual limb dressing state.
/datum/unit_test/medical_pain/proc/test_fracture()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/bodypart/arm = patient.get_bodypart(BODY_ZONE_R_ARM)
	var/datum/wound/blunt/bone/severe/fracture = new
	TEST_ASSERT(fracture.apply_wound(arm, silent = TRUE), "The fracture fixture must attach to its limb.")
	arm.heal_damage(INFINITY, INFINITY)
	patient.reagents.clear_reagents()
	patient.medical_pain.recalculate()
	var/untreated_pain = patient.medical_pain.raw_pain
	TEST_ASSERT(untreated_pain > 0, "An untreated fracture must hurt with healed brute damage.")
	var/obj/item/stack/medical/wrap/gauze/dressing = allocate(/obj/item/stack/medical/wrap/gauze)
	TEST_ASSERT(arm.apply_item(dressing, LIMB_ITEM_GAUZE), "The dressing fixture must attach.")
	patient.medical_pain.recalculate()
	TEST_ASSERT(patient.medical_pain.raw_pain < untreated_pain, "Splinting must reduce fracture pain without requiring new damage.")
	TEST_ASSERT(fracture in arm.wounds, "Symptom relief must not repair a fracture.")
	dressing.forceMove(run_loc_floor_bottom_left)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, untreated_pain, "Removing a splint must restore untreated fracture pain.")
	qdel(fracture)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 0, "Removing the repaired wound must clear the persistent surcharge.")

// Relief follows active metabolism, uses the strongest source, and disappears on purge.
/datum/unit_test/medical_pain/proc/test_analgesia()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	patient.reagents.add_reagent(/datum/reagent/medicine/granibitaluri, 10)
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 0, "An inactive reagent must not provide bloodstream relief.")
	var/datum/reagent/mild = patient.reagents.has_reagent(/datum/reagent/medicine/granibitaluri)
	mild.compute_metabolization(patient, SSMOBS_DT)
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 25, "Active mild medicine must provide finite relief.")
	TEST_ASSERT(!patient.has_surgical_analgesia(), "Mild medicine must not provide surgical anesthesia.")
	patient.reagents.add_reagent(/datum/reagent/medicine/morphine, 10)
	var/datum/reagent/strong = patient.reagents.has_reagent(/datum/reagent/medicine/morphine)
	strong.compute_metabolization(patient, SSMOBS_DT)
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 80, "Mixed analgesics must use the strongest source, not add strengths.")
	TEST_ASSERT(patient.has_surgical_analgesia(), "Morphine must retain surgical analgesia.")
	patient.reagents.remove_reagent(/datum/reagent/medicine/morphine, INFINITY)
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 25, "Purging the strongest source must expose remaining mild relief.")
	patient.reagents.end_metabolization(patient, keep_liverless = FALSE)
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 0, "Stopped metabolism must not retain analgesia.")
	patient.reagents.clear_reagents()
	TEST_ASSERT_EQUAL(patient.get_medical_pain_relief(), 0, "Purging all drugs must leave no stale relief.")

// Extra reads cannot accelerate stages, and recovery uses a separate threshold.
// Permitted life updates advance up to two stages; thresholds and hysteresis are unchanged.
/datum/unit_test/medical_pain/proc/test_stage_timing()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	patient.adjust_tox_loss(160)
	var/datum/medical_pain/pain_state = patient.medical_pain
	var/simulation_time = world.time + 2 SECONDS
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time)
	TEST_ASSERT_EQUAL(pain_state.stage, 2, "An injury must escalate by up to two stages per interval.")
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time)
	TEST_ASSERT_EQUAL(pain_state.stage, 2, "Repeated updates in the same interval must not escalate symptoms.")
	pain_state.recalculate(current_time = simulation_time + 2 SECONDS)
	TEST_ASSERT_EQUAL(pain_state.stage, 2, "A diagnostic refresh must not advance the stage.")
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time + 2 SECONDS)
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time + 4 SECONDS)
	TEST_ASSERT_EQUAL(pain_state.stage, 3, "Sustained forty-percent pain must reach stage three.")
	patient.adjust_tox_loss(-12)
	pain_state.recalculate()
	TEST_ASSERT_EQUAL(pain_state.stage, 3, "Thirty-seven-percent pain must stay within stage-three recovery hysteresis.")
	patient.adjust_tox_loss(-10)
	pain_state.recalculate()
	TEST_ASSERT_EQUAL(pain_state.stage, 2, "Pain below thirty-five percent must recover promptly to stage two.")
	ADD_TRAIT(patient, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	pain_state.recalculate()
	TEST_ASSERT(pain_state.raw_pain > 0, "Pain immunity must not heal the underlying injury.")
	TEST_ASSERT_EQUAL(pain_state.effective_pain, 0, "Explicit pain immunity must suppress effective pain.")
	TEST_ASSERT_EQUAL(pain_state.stage, 0, "Complete relief must clear symptom stage immediately.")

// Stasis, death and healing clear owned symptoms while preserving unrelated modifiers.
/datum/unit_test/medical_pain/proc/test_lifecycle()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/bodypart/arm = patient.get_bodypart(BODY_ZONE_R_ARM)
	arm.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	var/datum/medical_pain/pain_state = patient.medical_pain
	pain_state.recalculate(advance_stage = TRUE, current_time = world.time + 2 SECONDS)
	TEST_ASSERT(patient.has_status_effect(/datum/status_effect/medical_pain), "Pain symptoms must have a patient status.")
	patient.add_or_update_variable_movespeed_modifier(/datum/movespeed_modifier/admin_varedit, multiplicative_slowdown = 0.7)
	ADD_TRAIT(patient, TRAIT_STASIS, TRAIT_SOURCE_UNIT_TESTS)
	TEST_ASSERT_EQUAL(pain_state.stage, 0, "Entering stasis must clear symptoms immediately.")
	TEST_ASSERT(!patient.has_status_effect(/datum/status_effect/medical_pain), "Stasis must remove the pain alert.")
	TEST_ASSERT(patient.has_movespeed_modifier(/datum/movespeed_modifier/admin_varedit), "Pain cleanup must preserve unrelated movement modifiers.")
	REMOVE_TRAIT(patient, TRAIT_STASIS, TRAIT_SOURCE_UNIT_TESTS)
	TEST_ASSERT_EQUAL(pain_state.effective_pain, 48, "Leaving stasis must restore untreated injury pain.")
	pain_state.recalculate(advance_stage = TRUE, current_time = world.time + 4 SECONDS)
	patient.death()
	TEST_ASSERT_EQUAL(pain_state.stage, 0, "Death must clear pain symptoms immediately.")
	TEST_ASSERT(!patient.has_status_effect(/datum/status_effect/medical_pain), "Death must remove the pain alert.")
	patient.revive()
	TEST_ASSERT_EQUAL(pain_state.effective_pain, 48, "Revival without healing must resample the surviving injury.")
	pain_state.recalculate(advance_stage = TRUE, current_time = world.time + 6 SECONDS)
	patient.fully_heal(ADMIN_HEAL_ALL)
	TEST_ASSERT_EQUAL(pain_state.raw_pain, 0, "Full healing must resample the repaired body.")
	TEST_ASSERT_EQUAL(pain_state.stage, 0, "Full healing must clear pain symptoms.")

// Prosthetic injury is painless and synthetic species retain their original damage slowdown.
/datum/unit_test/medical_pain/proc/test_synthetic_bodies()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/bodypart/old_arm = patient.get_bodypart(BODY_ZONE_R_ARM)
	old_arm.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	patient.medical_pain.recalculate(advance_stage = TRUE, current_time = world.time + 2 SECONDS)
	var/obj/item/bodypart/arm/right/robot/prosthesis = allocate(/obj/item/bodypart/arm/right/robot)
	TEST_ASSERT(prosthesis.replace_limb(patient), "The prosthetic fixture must replace the injured arm.")
	qdel(old_arm)
	prosthesis.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, 0, "Damaged machinery must not cause organic pain.")
	TEST_ASSERT_EQUAL(patient.medical_pain.stage, 0, "Replacing the painful limb must clear symptoms.")
	patient.set_species(/datum/species/android)
	TEST_ASSERT(!patient.uses_medical_pain(), "Androids must opt out of organic pain.")
	patient.adjust_brute_loss(60)
	patient.medical_pain.recalculate(advance_stage = TRUE, current_time = world.time + 4 SECONDS)
	TEST_ASSERT_EQUAL(patient.medical_pain.stage, 0, "Synthetic damage must not escalate pain symptoms.")
	TEST_ASSERT(patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "Synthetic bodies must retain legacy damage impairment.")

// Dynamic fixtures: downstream maxHealth is 135 (HUMAN_HEALTH_MODIFIER), so limb/chest
// damage needed for crit scales with the live mob instead of magic 100-health numbers.
// Chest has body_damage_coeff 1, so chest brute maps 1:1 onto the health deficit.
/datum/unit_test/medical_pain/proc/soft_deficit(mob/living/carbon/human/patient)
	return patient.maxHealth - patient.crit_threshold + 5

/datum/unit_test/medical_pain/proc/hard_deficit(mob/living/carbon/human/patient)
	return patient.maxHealth - patient.hardcrit_threshold + 5

/datum/unit_test/medical_pain/proc/damage_chest_to_softcrit(mob/living/carbon/human/patient)
	patient.get_bodypart(BODY_ZONE_CHEST).receive_damage(brute = soft_deficit(patient), wound_bonus = CANT_WOUND)

/datum/unit_test/medical_pain/proc/damage_chest_to_hardcrit(mob/living/carbon/human/patient)
	patient.get_bodypart(BODY_ZONE_CHEST).receive_damage(brute = hard_deficit(patient), wound_bonus = CANT_WOUND)

// Fill capped organ pain without touching limb health: three severe organs for the full cap.
/datum/unit_test/medical_pain/proc/fill_organs_to_cap(mob/living/carbon/human/patient)
	for(var/organ_slot in list(ORGAN_SLOT_LIVER, ORGAN_SLOT_LUNGS, ORGAN_SLOT_STOMACH))
		var/obj/item/organ/damaged_organ = patient.get_organ_slot(organ_slot)
		patient.set_organ_loss(organ_slot, damaged_organ.high_threshold)

// Fill exactly thirty organ pain without touching limb health: severe liver plus half-severe stomach.
/datum/unit_test/medical_pain/proc/fill_organs_thirty(mob/living/carbon/human/patient)
	var/obj/item/organ/liver = patient.get_organ_slot(ORGAN_SLOT_LIVER)
	patient.set_organ_loss(ORGAN_SLOT_LIVER, liver.high_threshold)
	var/obj/item/organ/stomach = patient.get_organ_slot(ORGAN_SLOT_STOMACH)
	patient.set_organ_loss(ORGAN_SLOT_STOMACH, stomach.high_threshold * 0.5)

/datum/unit_test/medical_pain/proc/organ_pool_damage(mob/living/carbon/human/patient, list/slots)
	var/total = 0
	for(var/slot in slots)
		total += patient.get_organ_loss(slot) || 0
	return total

// Bearable injury below full capacity defers stock crit; pain at capacity restores it from fresh sampling, not visual stage.
/datum/unit_test/medical_pain/proc/test_crit_deferral()
	var/mob/living/carbon/human/soft_patient = allocate(/mob/living/carbon/human/consistent)
	var/soft_want = soft_deficit(soft_patient)
	damage_chest_to_softcrit(soft_patient)
	soft_patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(soft_patient.medical_pain.raw_pain, soft_want * 1.2, "Chest brute must sample with the 1.2 coefficient without wounds.")
	TEST_ASSERT(soft_patient.medical_pain.raw_pain < MEDICAL_PAIN_CAPACITY, "Softcrit fixture must stay below full capacity.")
	TEST_ASSERT(soft_patient.health <= soft_patient.crit_threshold, "Chest fixture must reach softcrit health.")
	TEST_ASSERT(soft_patient.health > soft_patient.hardcrit_threshold, "Chest fixture must stay above hardcrit health.")
	TEST_ASSERT(soft_patient.defers_injury_crit(), "Bearable softcrit pain must defer injury crit.")
	TEST_ASSERT_EQUAL(soft_patient.stat, STABLE, "Bearable softcrit injury must stay STABLE without analgesia.")
	var/mob/living/carbon/human/hard_patient = allocate(/mob/living/carbon/human/consistent)
	var/hard_want = hard_deficit(hard_patient)
	damage_chest_to_hardcrit(hard_patient)
	hard_patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(hard_patient.medical_pain.raw_pain, hard_want * 1.2, "Hardcrit chest brute must sample with the 1.2 coefficient without wounds.")
	TEST_ASSERT(hard_patient.medical_pain.raw_pain >= MEDICAL_PAIN_CAPACITY, "Bare hardcrit fixture must reach full capacity at default balance.")
	TEST_ASSERT(hard_patient.health <= hard_patient.hardcrit_threshold, "Chest fixture must reach hardcrit health.")
	TEST_ASSERT(!hard_patient.defers_injury_crit(), "Untreated hardcrit pain must not defer injury crit.")
	TEST_ASSERT_EQUAL(hard_patient.stat, HARD_CRIT, "Untreated hardcrit injury must stay in stock hardcrit without analgesia.")
	hard_patient.reagents.add_reagent(/datum/reagent/medicine/granibitaluri, 10)
	var/datum/reagent/hard_relief = hard_patient.reagents.has_reagent(/datum/reagent/medicine/granibitaluri)
	hard_relief.compute_metabolization(hard_patient, SSMOBS_DT)
	hard_patient.medical_pain.recalculate()
	TEST_ASSERT(hard_patient.defers_injury_crit(), "Finite mild relief must make hardcrit pain bearable.")
	TEST_ASSERT_EQUAL(hard_patient.stat, STABLE, "Finite mild relief must defer hardcrit injury without healing.")
	hard_patient.reagents.clear_reagents()
	var/mob/living/carbon/human/soft_collapse = allocate(/mob/living/carbon/human/consistent)
	var/soft_base = soft_deficit(soft_collapse)
	damage_chest_to_softcrit(soft_collapse)
	fill_organs_to_cap(soft_collapse)
	soft_collapse.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(soft_collapse.medical_pain.raw_pain, soft_base * 1.2 + MEDICAL_PAIN_ORGAN_CAP, "Chest plus three capped organs must sample scaled limb pain plus the organ cap.")
	TEST_ASSERT(soft_collapse.medical_pain.raw_pain >= MEDICAL_PAIN_CAPACITY, "Softcrit collapse fixture must reach full capacity.")
	TEST_ASSERT(soft_collapse.health <= soft_collapse.crit_threshold, "Collapse soft injury must stay in softcrit health.")
	TEST_ASSERT(!soft_collapse.defers_injury_crit(), "Full-capacity softcrit pain must not defer injury crit.")
	TEST_ASSERT_EQUAL(soft_collapse.stat, SOFT_CRIT, "Full-capacity softcrit injury must restore stock softcrit.")
	var/mob/living/carbon/human/hard_collapse = allocate(/mob/living/carbon/human/consistent)
	var/hard_base = hard_deficit(hard_collapse)
	damage_chest_to_hardcrit(hard_collapse)
	fill_organs_thirty(hard_collapse)
	hard_collapse.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(hard_collapse.medical_pain.raw_pain, hard_base * 1.2 + 30, "Hardcrit chest plus thirty organ pain must sample scaled limb pain plus organs.")
	TEST_ASSERT(hard_collapse.medical_pain.raw_pain >= MEDICAL_PAIN_CAPACITY, "Hardcrit collapse fixture must meet full capacity.")
	TEST_ASSERT(hard_collapse.health <= hard_collapse.hardcrit_threshold, "Collapse injury must stay in hardcrit health.")
	TEST_ASSERT(!hard_collapse.defers_injury_crit(), "Full-capacity hardcrit pain must resume stock crit.")
	TEST_ASSERT_EQUAL(hard_collapse.stat, HARD_CRIT, "Full-capacity hardcrit injury must restore stock hardcrit.")
	soft_patient.medical_pain.stage = 6
	soft_patient.update_stat()
	TEST_ASSERT_EQUAL(soft_patient.stat, STABLE, "Visual stage must not override fresh bearable sampling; the symptom scale still peaks at eighty percent independently.")
	TEST_ASSERT(soft_patient.defers_injury_crit(), "Bearable sampling must defer regardless of visual stage.")
	hard_collapse.medical_pain.stage = 0
	hard_collapse.update_stat()
	TEST_ASSERT_EQUAL(hard_collapse.stat, HARD_CRIT, "Visual recovery must not override fresh collapse sampling.")
	TEST_ASSERT(!hard_collapse.defers_injury_crit(), "Collapse sampling must crit regardless of visual stage.")

// Analgesia and finite medicine restore control without healing, and purging leaves no stale relief.
/datum/unit_test/medical_pain/proc/test_treatment_control()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	var/patient_want = hard_deficit(patient)
	damage_chest_to_hardcrit(patient)
	fill_organs_thirty(patient)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, patient_want * 1.2 + 30, "Collapse fixture must sample scaled limb pain plus thirty organ pain.")
	TEST_ASSERT(patient.medical_pain.raw_pain >= MEDICAL_PAIN_CAPACITY, "Collapse fixture must start at full capacity.")
	TEST_ASSERT_EQUAL(patient.stat, HARD_CRIT, "Full-capacity injury must start in stock hardcrit.")
	var/starting_brute = patient.get_brute_loss()
	var/starting_health = patient.health
	ADD_TRAIT(patient, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.medical_pain.raw_pain, patient_want * 1.2 + 30, "Trait relief must not heal underlying injury.")
	TEST_ASSERT_EQUAL(patient.medical_pain.effective_pain, 0, "Analgesia trait must suppress effective pain.")
	TEST_ASSERT_EQUAL(patient.get_brute_loss(), starting_brute, "Trait relief must restore control without healing limbs.")
	TEST_ASSERT_EQUAL(patient.health, starting_health, "Trait relief must restore control without healing health.")
	TEST_ASSERT_EQUAL(patient.stat, STABLE, "Trait relief must defer full-capacity hardcrit.")
	REMOVE_TRAIT(patient, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	patient.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(patient.stat, HARD_CRIT, "Removing trait relief must return stock hardcrit without new injury.")
	var/mob/living/carbon/human/soft_treated = allocate(/mob/living/carbon/human/consistent)
	var/soft_want = soft_deficit(soft_treated)
	damage_chest_to_softcrit(soft_treated)
	fill_organs_to_cap(soft_treated)
	soft_treated.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(soft_treated.medical_pain.raw_pain, soft_want * 1.2 + MEDICAL_PAIN_ORGAN_CAP, "Soft collapse fixture must sample scaled limb pain plus the organ cap.")
	TEST_ASSERT(soft_treated.medical_pain.raw_pain >= MEDICAL_PAIN_CAPACITY, "Soft collapse fixture must start at full capacity.")
	TEST_ASSERT_EQUAL(soft_treated.stat, SOFT_CRIT, "Soft collapse fixture must start in stock softcrit.")
	TEST_ASSERT(soft_treated.has_movespeed_modifier(/datum/movespeed_modifier/carbon_softcrit), "Stock softcrit must apply the softcrit movement modifier.")
	ADD_TRAIT(soft_treated, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	soft_treated.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(soft_treated.stat, STABLE, "Pain-only relief must return health crit to STABLE.")
	TEST_ASSERT(!soft_treated.has_movespeed_modifier(/datum/movespeed_modifier/carbon_softcrit), "Pain-only relief must remove the softcrit movement modifier.")
	REMOVE_TRAIT(soft_treated, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	soft_treated.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(soft_treated.stat, SOFT_CRIT, "Purging relief must restore stock softcrit.")
	TEST_ASSERT(soft_treated.has_movespeed_modifier(/datum/movespeed_modifier/carbon_softcrit), "Restored softcrit must restore the softcrit movement modifier.")
	var/mob/living/carbon/human/medicated = allocate(/mob/living/carbon/human/consistent)
	var/medicated_want = hard_deficit(medicated)
	damage_chest_to_hardcrit(medicated)
	fill_organs_thirty(medicated)
	medicated.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(medicated.medical_pain.raw_pain, medicated_want * 1.2 + 30, "Medicated fixture must sample scaled limb pain plus thirty organ pain.")
	TEST_ASSERT(medicated.medical_pain.raw_pain >= MEDICAL_PAIN_CAPACITY, "Medicated fixture must start at full capacity.")
	TEST_ASSERT_EQUAL(medicated.stat, HARD_CRIT, "Medicated fixture must start in stock hardcrit.")
	var/medicated_brute = medicated.get_brute_loss()
	var/medicated_health = medicated.health
	medicated.reagents.add_reagent(/datum/reagent/medicine/morphine, 10)
	var/datum/reagent/morphine = medicated.reagents.has_reagent(/datum/reagent/medicine/morphine)
	morphine.compute_metabolization(medicated, SSMOBS_DT)
	TEST_ASSERT_EQUAL(medicated.get_medical_pain_relief(), MEDICAL_PAIN_RELIEF_STRONG, "Active morphine must provide strong finite relief.")
	medicated.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(medicated.get_brute_loss(), medicated_brute, "Finite medicine must restore control without healing limbs.")
	TEST_ASSERT_EQUAL(medicated.health, medicated_health, "Finite medicine must restore control without healing health.")
	TEST_ASSERT_EQUAL(medicated.stat, STABLE, "Strong finite relief must defer full-capacity hardcrit.")
	medicated.reagents.remove_reagent(/datum/reagent/medicine/morphine, INFINITY)
	medicated.reagents.end_metabolization(medicated, keep_liverless = FALSE)
	medicated.reagents.clear_reagents()
	medicated.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(medicated.get_medical_pain_relief(), 0, "Purging finite medicine must leave no stale relief.")
	TEST_ASSERT_EQUAL(medicated.stat, HARD_CRIT, "Purging finite relief must return stock hardcrit.")

// Physiological-only crit never defers, and death still applies.
/datum/unit_test/medical_pain/proc/test_physiological_guards()
	var/mob/living/carbon/human/oxy_patient = allocate(/mob/living/carbon/human/consistent)
	oxy_patient.adjust_oxy_loss(oxy_patient.maxHealth - oxy_patient.crit_threshold + 1)
	oxy_patient.medical_pain.recalculate()
	TEST_ASSERT(oxy_patient.health <= oxy_patient.crit_threshold, "Oxygen fixture must reach crit health.")
	TEST_ASSERT(!oxy_patient.defers_injury_crit(), "Pure oxygen crit must not defer.")
	TEST_ASSERT_EQUAL(oxy_patient.stat, SOFT_CRIT, "Pure oxygen softcrit must use stock crit.")
	var/mob/living/carbon/human/tox_patient = allocate(/mob/living/carbon/human/consistent)
	tox_patient.adjust_tox_loss(tox_patient.maxHealth - tox_patient.crit_threshold + 1)
	tox_patient.medical_pain.recalculate()
	TEST_ASSERT(tox_patient.health <= tox_patient.crit_threshold, "Toxin fixture must reach crit health.")
	TEST_ASSERT(!tox_patient.defers_injury_crit(), "Pure toxin crit must not defer.")
	TEST_ASSERT_EQUAL(tox_patient.stat, SOFT_CRIT, "Pure toxin softcrit must use stock crit.")
	var/mob/living/carbon/human/dying = allocate(/mob/living/carbon/human/consistent)
	dying.get_bodypart(BODY_ZONE_CHEST).receive_damage(brute = dying.maxHealth - HEALTH_THRESHOLD_DEAD + 5, wound_bonus = CANT_WOUND)
	TEST_ASSERT(dying.health <= HEALTH_THRESHOLD_DEAD, "Chest fixture must reach the death threshold.")
	TEST_ASSERT_EQUAL(dying.stat, DEAD, "Death threshold must not be bypassed by pain deferral.")
	TEST_ASSERT(!dying.defers_injury_crit(), "Death must never defer.")

// Missing or failing heart, lungs, or brain never defers, including cardiac arrest.
/datum/unit_test/medical_pain/proc/test_organ_guards()
	var/mob/living/carbon/human/heart_missing = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(heart_missing)
	var/obj/item/organ/heart/missing_heart = heart_missing.get_organ_slot(ORGAN_SLOT_HEART)
	missing_heart.Remove(heart_missing)
	heart_missing.medical_pain.recalculate()
	TEST_ASSERT(!heart_missing.defers_injury_crit(), "Missing heart must not defer.")
	TEST_ASSERT_EQUAL(heart_missing.stat, SOFT_CRIT, "Missing heart must use stock softcrit.")
	qdel(missing_heart)
	var/mob/living/carbon/human/heart_failing = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(heart_failing)
	var/obj/item/organ/heart/failing_heart = heart_failing.get_organ_slot(ORGAN_SLOT_HEART)
	heart_failing.set_organ_loss(ORGAN_SLOT_HEART, failing_heart.maxHealth)
	heart_failing.medical_pain.recalculate()
	TEST_ASSERT(!heart_failing.defers_injury_crit(), "Failing heart must not defer.")
	TEST_ASSERT_EQUAL(heart_failing.stat, SOFT_CRIT, "Failing heart must use stock softcrit.")
	var/mob/living/carbon/human/lungs_missing = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(lungs_missing)
	var/obj/item/organ/lungs/missing_lungs = lungs_missing.get_organ_slot(ORGAN_SLOT_LUNGS)
	missing_lungs.Remove(lungs_missing)
	lungs_missing.medical_pain.recalculate()
	TEST_ASSERT(!lungs_missing.defers_injury_crit(), "Missing lungs must not defer.")
	TEST_ASSERT_EQUAL(lungs_missing.stat, SOFT_CRIT, "Missing lungs must use stock softcrit.")
	qdel(missing_lungs)
	var/mob/living/carbon/human/lungs_failing = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(lungs_failing)
	var/obj/item/organ/lungs/failing_lungs = lungs_failing.get_organ_slot(ORGAN_SLOT_LUNGS)
	lungs_failing.set_organ_loss(ORGAN_SLOT_LUNGS, failing_lungs.maxHealth)
	lungs_failing.medical_pain.recalculate()
	TEST_ASSERT(!lungs_failing.defers_injury_crit(), "Failing lungs must not defer.")
	TEST_ASSERT_EQUAL(lungs_failing.stat, SOFT_CRIT, "Failing lungs must use stock softcrit.")
	var/mob/living/carbon/human/brain_missing = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(brain_missing)
	var/obj/item/organ/brain/missing_brain = brain_missing.get_organ_slot(ORGAN_SLOT_BRAIN)
	missing_brain.Remove(brain_missing)
	brain_missing.medical_pain.recalculate()
	TEST_ASSERT(!brain_missing.defers_injury_crit(), "Missing vital brain must not defer.")
	TEST_ASSERT_EQUAL(brain_missing.stat, DEAD, "Losing the vital brain must kill via stock vital-organ death, not softcrit.")
	qdel(missing_brain)
	var/mob/living/carbon/human/brain_failing = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(brain_failing)
	var/obj/item/organ/brain/failing_brain = brain_failing.get_organ_slot(ORGAN_SLOT_BRAIN)
	brain_failing.set_organ_loss(ORGAN_SLOT_BRAIN, failing_brain.maxHealth)
	// Random damage traumas such as Tenacity can independently disable health crit.
	failing_brain.cure_all_traumas(TRAUMA_RESILIENCE_ABSOLUTE)
	brain_failing.medical_pain.recalculate()
	TEST_ASSERT(!brain_failing.defers_injury_crit(), "Failing brain must not defer.")
	TEST_ASSERT_EQUAL(brain_failing.stat, SOFT_CRIT, "Failing brain must use stock softcrit.")
	ADD_TRAIT(failing_brain, TRAIT_BRAIN_DAMAGE_NODEATH, TRAIT_SOURCE_UNIT_TESTS)
	brain_failing.medical_pain.recalculate()
	TEST_ASSERT(brain_failing.defers_injury_crit(), "Failing brain with the stock organ-level no-death exemption must defer like bearable injury.")
	TEST_ASSERT_EQUAL(brain_failing.stat, STABLE, "Exempted failing brain must stay STABLE at bearable pain.")
	REMOVE_TRAIT(failing_brain, TRAIT_BRAIN_DAMAGE_NODEATH, TRAIT_SOURCE_UNIT_TESTS)
	brain_failing.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(brain_failing.stat, SOFT_CRIT, "Clearing the organ exemption must restore stock softcrit.")
	var/mob/living/carbon/human/arrested = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(arrested)
	var/obj/item/organ/heart/arrested_heart = arrested.get_organ_slot(ORGAN_SLOT_HEART)
	TEST_ASSERT(arrested_heart.Stop(), "Arrest fixture must stop the heart.")
	TEST_ASSERT(arrested.undergoing_cardiac_arrest(), "Stopped heart must read as cardiac arrest.")
	arrested.medical_pain.recalculate()
	TEST_ASSERT(!arrested.defers_injury_crit(), "Cardiac arrest must not defer.")
	TEST_ASSERT_EQUAL(arrested.stat, SOFT_CRIT, "Cardiac arrest must use stock softcrit.")

// Pain sampling must preserve unrelated sleep, stun, stamcrit, and oxygen unconsciousness.
/datum/unit_test/medical_pain/proc/test_unrelated_preservation()
	var/mob/living/carbon/human/stunned = allocate(/mob/living/carbon/human/consistent)
	stunned.Stun(20 SECONDS)
	var/obj/item/bodypart/stunned_arm = stunned.get_bodypart(BODY_ZONE_R_ARM)
	stunned_arm.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	stunned.medical_pain.recalculate(advance_stage = TRUE, current_time = world.time + 2 SECONDS)
	TEST_ASSERT(stunned.IsStun(), "Pain sampling must not erase stun.")
	TEST_ASSERT_EQUAL(stunned.medical_pain.raw_pain, 48, "Stun fixture must preserve scaled injury sampling.")
	var/mob/living/carbon/human/knocked = allocate(/mob/living/carbon/human/consistent)
	knocked.Unconscious(20 SECONDS)
	var/obj/item/bodypart/knocked_arm = knocked.get_bodypart(BODY_ZONE_R_ARM)
	knocked_arm.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	knocked.medical_pain.recalculate(advance_stage = TRUE, current_time = world.time + 2 SECONDS)
	TEST_ASSERT(knocked.IsUnconscious(), "Pain sampling must not erase unconsciousness.")
	var/mob/living/carbon/human/exhausted = allocate(/mob/living/carbon/human/consistent)
	exhausted.adjust_stamina_loss(exhausted.maxHealth - exhausted.crit_threshold)
	TEST_ASSERT(exhausted.has_status_effect(/datum/status_effect/incapacitating/stamcrit), "Stamina fixture must reach stamcrit.")
	var/obj/item/bodypart/exhausted_arm = exhausted.get_bodypart(BODY_ZONE_R_ARM)
	exhausted_arm.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	exhausted.medical_pain.recalculate(advance_stage = TRUE, current_time = world.time + 2 SECONDS)
	TEST_ASSERT(exhausted.has_status_effect(/datum/status_effect/incapacitating/stamcrit), "Pain sampling must not erase stamcrit.")
	var/mob/living/carbon/human/sleeping = allocate(/mob/living/carbon/human/consistent)
	sleeping.apply_status_effect(/datum/status_effect/incapacitating/sleeping, 20 SECONDS)
	var/obj/item/bodypart/sleeping_arm = sleeping.get_bodypart(BODY_ZONE_R_ARM)
	sleeping_arm.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	sleeping.medical_pain.recalculate(advance_stage = TRUE, current_time = world.time + 2 SECONDS)
	TEST_ASSERT(sleeping.has_status_effect(/datum/status_effect/incapacitating/sleeping), "Pain sampling must not erase sleep.")
	var/mob/living/carbon/human/oxy_unconscious = allocate(/mob/living/carbon/human/consistent)
	oxy_unconscious.adjust_oxy_loss(50)
	oxy_unconscious.Unconscious(20 SECONDS)
	var/obj/item/bodypart/oxy_arm = oxy_unconscious.get_bodypart(BODY_ZONE_R_ARM)
	oxy_arm.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	oxy_unconscious.medical_pain.recalculate(advance_stage = TRUE, current_time = world.time + 2 SECONDS)
	TEST_ASSERT(oxy_unconscious.IsUnconscious(), "Pain sampling must not erase oxygen unconsciousness.")
	TEST_ASSERT_EQUAL(oxy_unconscious.get_oxy_loss(), 50, "Pain sampling must preserve oxygen damage.")
	TEST_ASSERT_EQUAL(oxy_unconscious.medical_pain.raw_pain, 48, "Oxygen damage must not become injury pain.")
	var/mob/living/carbon/human/crit_stunned = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(crit_stunned)
	fill_organs_to_cap(crit_stunned)
	crit_stunned.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(crit_stunned.stat, SOFT_CRIT, "Crit-transition fixture must start in stock softcrit.")
	crit_stunned.Stun(20 SECONDS)
	crit_stunned.apply_status_effect(/datum/status_effect/incapacitating/sleeping, 20 SECONDS)
	ADD_TRAIT(crit_stunned, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	crit_stunned.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(crit_stunned.stat, STABLE, "Analgesia must move actual health crit to STABLE without healing.")
	TEST_ASSERT(crit_stunned.IsStun(), "Crit-to-stable relief must preserve stun.")
	TEST_ASSERT(crit_stunned.has_status_effect(/datum/status_effect/incapacitating/sleeping), "Crit-to-stable relief must preserve sleep.")
	REMOVE_TRAIT(crit_stunned, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	crit_stunned.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(crit_stunned.stat, SOFT_CRIT, "Purging relief must return actual crit.")
	TEST_ASSERT(crit_stunned.IsStun(), "Returned crit must still preserve stun.")
	var/mob/living/carbon/human/crit_tired = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(crit_tired)
	fill_organs_to_cap(crit_tired)
	crit_tired.medical_pain.recalculate()
	crit_tired.adjust_stamina_loss(crit_tired.maxHealth - crit_tired.crit_threshold)
	crit_tired.Unconscious(20 SECONDS)
	ADD_TRAIT(crit_tired, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	crit_tired.medical_pain.recalculate()
	TEST_ASSERT_EQUAL(crit_tired.stat, STABLE, "Analgesia must move exhausted crit to STABLE without healing.")
	TEST_ASSERT(crit_tired.has_status_effect(/datum/status_effect/incapacitating/stamcrit), "Crit-to-stable relief must preserve stamcrit.")
	TEST_ASSERT(crit_tired.IsUnconscious(), "Crit-to-stable relief must preserve unconsciousness.")
	REMOVE_TRAIT(crit_tired, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	crit_tired.medical_pain.recalculate()
	TEST_ASSERT(crit_tired.has_status_effect(/datum/status_effect/incapacitating/stamcrit), "Returned crit must still preserve stamcrit.")

// Overflow uses the pre-hit health snapshot: twenty-five percent at softcrit, fifty percent at hardcrit.
/datum/unit_test/medical_pain/proc/test_overflow_shares()
	var/list/head_slots = list(ORGAN_SLOT_BRAIN, ORGAN_SLOT_EYES, ORGAN_SLOT_EARS)
	var/mob/living/carbon/human/soft_share = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(soft_share)
	TEST_ASSERT(soft_share.health <= soft_share.crit_threshold, "Chest fixture must reach softcrit pre-hit health.")
	TEST_ASSERT(soft_share.health > soft_share.hardcrit_threshold, "Chest fixture must stay above hardcrit pre-hit health.")
	var/soft_pool_before = 0
	var/list/soft_slot_before = list()
	for(var/slot in head_slots)
		var/slot_damage = soft_share.get_organ_loss(slot)
		soft_slot_before[slot] = slot_damage
		soft_pool_before += slot_damage
	soft_share.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	var/soft_pool_after = 0
	var/list/soft_pool_changed = list()
	for(var/slot in head_slots)
		var/slot_damage = soft_share.get_organ_loss(slot)
		soft_pool_after += slot_damage
		if(slot_damage != soft_slot_before[slot])
			soft_pool_changed += slot
	TEST_ASSERT_EQUAL(soft_pool_after - soft_pool_before, round(40 * MEDICAL_PAIN_OVERFLOW_SOFT_SHARE, DAMAGE_PRECISION), "Softcrit head overflow must use the twenty-five percent share.")
	TEST_ASSERT_EQUAL(length(soft_pool_changed), 1, "Head overflow must damage exactly one eligible head organ.")
	TEST_ASSERT(soft_pool_changed[1] in head_slots, "Head overflow must stay within brain, eyes, and ears.")
	var/mob/living/carbon/human/hard_share = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_hardcrit(hard_share)
	TEST_ASSERT(hard_share.health <= hard_share.hardcrit_threshold, "Chest fixture must reach hardcrit pre-hit health.")
	var/list/chest_pool = list(ORGAN_SLOT_HEART, ORGAN_SLOT_LUNGS, ORGAN_SLOT_LIVER, ORGAN_SLOT_STOMACH, ORGAN_SLOT_APPENDIX)
	var/hard_pool_before = 0
	var/list/hard_slot_before = list()
	for(var/slot in chest_pool)
		var/slot_damage = hard_share.get_organ_loss(slot)
		hard_slot_before[slot] = slot_damage
		hard_pool_before += slot_damage
	hard_share.apply_damage(damage = 40, damagetype = BRUTE, def_zone = BODY_ZONE_CHEST, wound_bonus = CANT_WOUND)
	var/hard_pool_after = 0
	var/list/hard_pool_changed = list()
	for(var/slot in chest_pool)
		var/slot_damage = hard_share.get_organ_loss(slot)
		hard_pool_after += slot_damage
		if(slot_damage != hard_slot_before[slot])
			hard_pool_changed += slot
	TEST_ASSERT_EQUAL(hard_pool_after - hard_pool_before, round(40 * MEDICAL_PAIN_OVERFLOW_HARD_SHARE, DAMAGE_PRECISION), "Hardcrit chest overflow must use the fifty percent share.")
	TEST_ASSERT_EQUAL(length(hard_pool_changed), 1, "Chest overflow must damage exactly one eligible chest organ.")
	TEST_ASSERT(hard_pool_changed[1] in chest_pool, "Chest overflow must stay within heart, lungs, liver, stomach, and appendix.")
	var/mob/living/carbon/human/healthy = allocate(/mob/living/carbon/human/consistent)
	healthy.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	var/healthy_head_total = organ_pool_damage(healthy, head_slots)
	TEST_ASSERT_EQUAL(healthy_head_total, 0, "Healthy head hits must not overflow.")
	var/mob/living/carbon/human/limb_hit = allocate(/mob/living/carbon/human/consistent)
	limb_hit.get_bodypart(BODY_ZONE_R_ARM).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	limb_hit.get_bodypart(BODY_ZONE_L_ARM).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	limb_hit.get_bodypart(BODY_ZONE_R_LEG).receive_damage(brute = 30, wound_bonus = CANT_WOUND)
	limb_hit.get_bodypart(BODY_ZONE_L_LEG).receive_damage(brute = 30, wound_bonus = CANT_WOUND)
	limb_hit.get_bodypart(BODY_ZONE_R_ARM).receive_damage(brute = 20, wound_bonus = CANT_WOUND)
	var/limb_head_total = organ_pool_damage(limb_hit, head_slots)
	var/limb_chest_total = organ_pool_damage(limb_hit, chest_pool)
	TEST_ASSERT_EQUAL(limb_head_total, 0, "Limb hits must not overflow to head organs.")
	TEST_ASSERT_EQUAL(limb_chest_total, 0, "Limb hits must not overflow to chest organs.")
	var/mob/living/carbon/human/unconscious_share = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(unconscious_share)
	unconscious_share.Unconscious(20 SECONDS)
	var/unconscious_before = organ_pool_damage(unconscious_share, head_slots)
	unconscious_share.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	var/unconscious_after = organ_pool_damage(unconscious_share, head_slots)
	TEST_ASSERT(unconscious_share.IsUnconscious(), "Overflow fixture must stay unconscious.")
	TEST_ASSERT_EQUAL(unconscious_after - unconscious_before, round(40 * MEDICAL_PAIN_OVERFLOW_SOFT_SHARE, DAMAGE_PRECISION), "Unconscious crit must still apply overflow.")

// Overflow guards: blocked, godmode, stasis, synthetic, ineligible organs, and saturated limbs.
/datum/unit_test/medical_pain/proc/test_overflow_guards()
	var/list/head_slots = list(ORGAN_SLOT_BRAIN, ORGAN_SLOT_EYES, ORGAN_SLOT_EARS)
	var/mob/living/carbon/human/blocked = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(blocked)
	blocked.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, blocked = 100, wound_bonus = CANT_WOUND)
	var/blocked_total = organ_pool_damage(blocked, head_slots)
	TEST_ASSERT_EQUAL(blocked_total, 0, "Fully blocked hits must not overflow.")
	var/mob/living/carbon/human/godmode = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(godmode)
	ADD_TRAIT(godmode, TRAIT_GODMODE, TRAIT_SOURCE_UNIT_TESTS)
	godmode.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	var/godmode_total = organ_pool_damage(godmode, head_slots)
	TEST_ASSERT_EQUAL(godmode_total, 0, "Godmode hits must not overflow.")
	REMOVE_TRAIT(godmode, TRAIT_GODMODE, TRAIT_SOURCE_UNIT_TESTS)
	var/mob/living/carbon/human/stasis = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(stasis)
	ADD_TRAIT(stasis, TRAIT_STASIS, TRAIT_SOURCE_UNIT_TESTS)
	stasis.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	var/stasis_total = organ_pool_damage(stasis, head_slots)
	TEST_ASSERT_EQUAL(stasis_total, 0, "Stasis hits must not overflow.")
	REMOVE_TRAIT(stasis, TRAIT_STASIS, TRAIT_SOURCE_UNIT_TESTS)
	var/mob/living/carbon/human/synthetic = allocate(/mob/living/carbon/human/consistent)
	synthetic.set_species(/datum/species/android)
	damage_chest_to_softcrit(synthetic)
	synthetic.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	var/synthetic_total = organ_pool_damage(synthetic, head_slots)
	TEST_ASSERT(!synthetic.uses_medical_pain(), "Android fixture must opt out of medical pain.")
	TEST_ASSERT_EQUAL(synthetic_total, 0, "Nonorganic hits must not overflow.")
	var/mob/living/carbon/human/isolated = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(isolated)
	var/obj/item/organ/eyes/isolated_eyes = isolated.get_organ_slot(ORGAN_SLOT_EYES)
	var/obj/item/organ/ears/isolated_ears = isolated.get_organ_slot(ORGAN_SLOT_EARS)
	isolated_eyes.Remove(isolated)
	isolated_ears.Remove(isolated)
	TEST_ASSERT(isnull(isolated.get_organ_slot(ORGAN_SLOT_EYES)), "Eye removal must isolate the brain candidate.")
	TEST_ASSERT(isnull(isolated.get_organ_slot(ORGAN_SLOT_EARS)), "Ear removal must isolate the brain candidate.")
	var/isolated_brain_before = isolated.get_organ_loss(ORGAN_SLOT_BRAIN)
	isolated.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	TEST_ASSERT_EQUAL(isolated.get_organ_loss(ORGAN_SLOT_BRAIN) - isolated_brain_before, round(40 * MEDICAL_PAIN_OVERFLOW_SOFT_SHARE, DAMAGE_PRECISION), "Isolated brain must take the full soft share.")
	qdel(isolated_eyes)
	qdel(isolated_ears)
	var/mob/living/carbon/human/robotic_guard = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(robotic_guard)
	var/obj/item/organ/eyes/robotic_eyes = robotic_guard.get_organ_slot(ORGAN_SLOT_EYES)
	var/obj/item/organ/ears/robotic_ears = robotic_guard.get_organ_slot(ORGAN_SLOT_EARS)
	robotic_eyes.organ_flags |= ORGAN_ROBOTIC
	robotic_ears.organ_flags |= ORGAN_ROBOTIC
	var/robotic_brain_before = robotic_guard.get_organ_loss(ORGAN_SLOT_BRAIN)
	var/robotic_eyes_before = robotic_guard.get_organ_loss(ORGAN_SLOT_EYES)
	var/robotic_ears_before = robotic_guard.get_organ_loss(ORGAN_SLOT_EARS)
	robotic_guard.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	TEST_ASSERT_EQUAL(robotic_guard.get_organ_loss(ORGAN_SLOT_EYES) - robotic_eyes_before, 0, "Robotic eyes must be excluded.")
	TEST_ASSERT_EQUAL(robotic_guard.get_organ_loss(ORGAN_SLOT_EARS) - robotic_ears_before, 0, "Robotic ears must be excluded.")
	TEST_ASSERT_EQUAL(robotic_guard.get_organ_loss(ORGAN_SLOT_BRAIN) - robotic_brain_before, round(40 * MEDICAL_PAIN_OVERFLOW_SOFT_SHARE, DAMAGE_PRECISION), "Eligible brain must take the share when others are robotic.")
	var/mob/living/carbon/human/failed_guard = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(failed_guard)
	var/obj/item/organ/eyes/failed_eyes = failed_guard.get_organ_slot(ORGAN_SLOT_EYES)
	var/obj/item/organ/ears/failed_ears = failed_guard.get_organ_slot(ORGAN_SLOT_EARS)
	failed_guard.set_organ_loss(ORGAN_SLOT_EYES, failed_eyes.maxHealth)
	failed_guard.set_organ_loss(ORGAN_SLOT_EARS, failed_ears.maxHealth)
	var/failed_brain_before = failed_guard.get_organ_loss(ORGAN_SLOT_BRAIN)
	failed_guard.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	TEST_ASSERT_EQUAL(failed_guard.get_organ_loss(ORGAN_SLOT_BRAIN) - failed_brain_before, round(40 * MEDICAL_PAIN_OVERFLOW_SOFT_SHARE, DAMAGE_PRECISION), "Eligible brain must take the share when others are failing or maxed.")
	TEST_ASSERT(failed_guard.get_organ_loss(ORGAN_SLOT_EYES) >= failed_eyes.maxHealth, "Failing or maxed eyes must stay maxed.")
	TEST_ASSERT(failed_guard.get_organ_loss(ORGAN_SLOT_EARS) >= failed_ears.maxHealth, "Failing or maxed ears must stay maxed.")
	var/mob/living/carbon/human/saturated = allocate(/mob/living/carbon/human/consistent)
	ADD_TRAIT(saturated, TRAIT_NODEATH, TRAIT_SOURCE_UNIT_TESTS)
	ADD_TRAIT(saturated, TRAIT_NODISMEMBER, TRAIT_SOURCE_UNIT_TESTS)
	var/obj/item/bodypart/saturated_head = saturated.get_bodypart(BODY_ZONE_HEAD)
	var/saturated_cap = saturated_head.max_damage
	saturated_head.receive_damage(brute = saturated_cap, wound_bonus = CANT_WOUND)
	TEST_ASSERT_EQUAL(saturated_head.get_damage(), saturated_cap, "Saturation fixture must cap the head limb.")
	TEST_ASSERT(saturated.health <= saturated.hardcrit_threshold, "Saturated fixture must stay in hardcrit pre-hit health.")
	var/saturated_pool_before = 0
	var/list/saturated_before = list()
	for(var/slot in head_slots)
		var/slot_damage = saturated.get_organ_loss(slot)
		saturated_before[slot] = slot_damage
		saturated_pool_before += slot_damage
	saturated_head.receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	TEST_ASSERT_EQUAL(saturated_head.get_damage(), saturated_cap, "Saturated head must keep limb damage capped.")
	var/saturated_pool_after = 0
	var/saturated_changed = 0
	for(var/slot in head_slots)
		var/slot_damage = saturated.get_organ_loss(slot)
		saturated_pool_after += slot_damage
		if(slot_damage != saturated_before[slot])
			saturated_changed += 1
	TEST_ASSERT_EQUAL(saturated_pool_after - saturated_pool_before, round(40 * MEDICAL_PAIN_OVERFLOW_HARD_SHARE, DAMAGE_PRECISION), "Saturated head must still overflow at the hard share.")
	TEST_ASSERT_EQUAL(saturated_changed, 1, "Saturated overflow must damage exactly one eligible organ.")
	REMOVE_TRAIT(saturated, TRAIT_NODEATH, TRAIT_SOURCE_UNIT_TESTS)
	REMOVE_TRAIT(saturated, TRAIT_NODISMEMBER, TRAIT_SOURCE_UNIT_TESTS)
	var/mob/living/carbon/human/mitigated = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(mitigated)
	mitigated.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, blocked = 50, wound_bonus = CANT_WOUND)
	var/mitigated_total = organ_pool_damage(mitigated, head_slots)
	TEST_ASSERT_EQUAL(mitigated_total, round(20 * MEDICAL_PAIN_OVERFLOW_SOFT_SHARE, DAMAGE_PRECISION), "Partial block must overflow from post-mitigation damage.")
	var/cancel_before = mitigated_total
	mitigated.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, required_bodytype = BODYTYPE_ROBOTIC, wound_bonus = CANT_WOUND)
	var/cancel_after = organ_pool_damage(mitigated, head_slots)
	TEST_ASSERT_EQUAL(cancel_after - cancel_before, 0, "Bodytype-cancelled limb damage must not overflow.")
	var/mob/living/carbon/human/burn_share = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(burn_share)
	burn_share.get_bodypart(BODY_ZONE_HEAD).receive_damage(burn = 40, wound_bonus = CANT_WOUND)
	var/burn_total = organ_pool_damage(burn_share, head_slots)
	TEST_ASSERT_EQUAL(burn_total, round(40 * MEDICAL_PAIN_OVERFLOW_SOFT_SHARE, DAMAGE_PRECISION), "Burn overflow must share the same post-mitigation pool as brute.")
	var/mob/living/carbon/human/relieved_share = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_softcrit(relieved_share)
	ADD_TRAIT(relieved_share, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	relieved_share.get_bodypart(BODY_ZONE_HEAD).receive_damage(brute = 40, wound_bonus = CANT_WOUND)
	var/relieved_total = organ_pool_damage(relieved_share, head_slots)
	TEST_ASSERT_EQUAL(relieved_total, round(40 * MEDICAL_PAIN_OVERFLOW_SOFT_SHARE, DAMAGE_PRECISION), "Overflow must ignore analgesia.")
	TEST_ASSERT_EQUAL(relieved_share.stat, STABLE, "Analgesia must defer despite overflow injury.")
	REMOVE_TRAIT(relieved_share, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)

// Ninety-percent pain must ramp 0 to 2 to 4 to 6 across gated life updates, then recover by hysteresis.
/datum/unit_test/medical_pain/proc/test_high_pain_ramp()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	var/obj/item/bodypart/chest = patient.get_bodypart(BODY_ZONE_CHEST)
	chest.receive_damage(brute = 150, wound_bonus = CANT_WOUND)
	var/datum/medical_pain/pain_state = patient.medical_pain
	pain_state.recalculate()
	TEST_ASSERT_EQUAL(pain_state.raw_pain, 180, "Scaled chest injury must sample at ninety percent.")
	TEST_ASSERT_EQUAL(pain_state.stage, 0, "Sampling without life processing must not advance stages.")
	var/simulation_time = world.time + 2 SECONDS
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time)
	TEST_ASSERT_EQUAL(pain_state.stage, 2, "The first permitted update must reach stage two.")
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time + 2 SECONDS)
	TEST_ASSERT_EQUAL(pain_state.stage, 4, "The second permitted update must reach stage four.")
	pain_state.recalculate(advance_stage = TRUE, current_time = simulation_time + 4 SECONDS)
	TEST_ASSERT_EQUAL(pain_state.stage, 6, "The third permitted update must reach stage six.")
	var/datum/movespeed_modifier/pain_modifier = patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown)
	TEST_ASSERT_NOTNULL(pain_modifier, "Overwhelming pain must apply movement impairment.")
	TEST_ASSERT_EQUAL(pain_modifier.multiplicative_slowdown, 3, "Overwhelming pain must use the increased slowdown, not stack with the hardcrit floor.")
	chest.heal_damage(20, 0)
	pain_state.recalculate()
	TEST_ASSERT_EQUAL(pain_state.stage, 6, "Seventy-eight-percent pain must hold stage six within hysteresis.")
	chest.heal_damage(15, 0)
	pain_state.recalculate()
	TEST_ASSERT_EQUAL(pain_state.stage, 5, "Pain below seventy-five percent must recover promptly to stage five.")
	TEST_ASSERT_EQUAL(pain_modifier.multiplicative_slowdown, 2.25, "Intense pain must use the increased movement slowdown.")

// Hardcrit-range health keeps a movement floor under analgesia; exemptions clear it.
/datum/unit_test/medical_pain/proc/test_hardcrit_floors()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_hardcrit(patient)
	TEST_ASSERT(patient.health <= patient.hardcrit_threshold, "Hardcrit fixture must reach hardcrit health.")
	patient.medical_pain.recalculate()
	var/datum/movespeed_modifier/floor_modifier = patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown)
	TEST_ASSERT_NOTNULL(floor_modifier, "Hardcrit health must apply the damage slowdown modifier.")
	TEST_ASSERT_EQUAL(floor_modifier.multiplicative_slowdown, MEDICAL_PAIN_HARDCRIT_SLOWDOWN, "Hardcrit health must floor movement impairment at 1.5.")
	ADD_TRAIT(patient, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	patient.medical_pain.recalculate()
	floor_modifier = patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown)
	TEST_ASSERT_NOTNULL(floor_modifier, "Trait relief must not remove the hardcrit-health floor.")
	TEST_ASSERT_EQUAL(floor_modifier.multiplicative_slowdown, MEDICAL_PAIN_HARDCRIT_SLOWDOWN, "Trait relief must not lower the hardcrit-health floor.")
	TEST_ASSERT(patient.defers_injury_crit(), "Pain relief must preserve control at hardcrit health.")
	patient.get_bodypart(BODY_ZONE_CHEST).heal_damage(10, 0)
	TEST_ASSERT(patient.health > patient.hardcrit_threshold, "Partial healing must leave hardcrit health.")
	TEST_ASSERT(!patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "The floor must clear above hardcrit health while pain is suppressed.")
	REMOVE_TRAIT(patient, TRAIT_ANALGESIA, TRAIT_SOURCE_UNIT_TESTS)
	var/mob/living/carbon/human/medicated = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_hardcrit(medicated)
	medicated.reagents.add_reagent(/datum/reagent/medicine/morphine, 10)
	var/datum/reagent/morphine = medicated.reagents.has_reagent(/datum/reagent/medicine/morphine)
	morphine.compute_metabolization(medicated, SSMOBS_DT)
	medicated.medical_pain.recalculate()
	floor_modifier = medicated.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown)
	TEST_ASSERT_NOTNULL(floor_modifier, "Finite relief must not remove the hardcrit-health floor.")
	TEST_ASSERT_EQUAL(floor_modifier.multiplicative_slowdown, MEDICAL_PAIN_HARDCRIT_SLOWDOWN, "Finite relief must not lower the hardcrit-health floor.")
	medicated.reagents.clear_reagents()
	patient.fully_heal(ADMIN_HEAL_ALL)
	TEST_ASSERT(!patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "Full healing must clear the hardcrit-health floor.")
	var/mob/living/carbon/human/stasis_patient = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_hardcrit(stasis_patient)
	ADD_TRAIT(stasis_patient, TRAIT_STASIS, TRAIT_SOURCE_UNIT_TESTS)
	TEST_ASSERT(!stasis_patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "Stasis must clear the hardcrit-health floor.")
	REMOVE_TRAIT(stasis_patient, TRAIT_STASIS, TRAIT_SOURCE_UNIT_TESTS)
	var/mob/living/carbon/human/godmode_patient = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_hardcrit(godmode_patient)
	godmode_patient.medical_pain.recalculate()
	ADD_TRAIT(godmode_patient, TRAIT_GODMODE, TRAIT_SOURCE_UNIT_TESTS)
	godmode_patient.medical_pain.recalculate()
	TEST_ASSERT(!godmode_patient.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "Godmode must clear the hardcrit-health floor.")
	REMOVE_TRAIT(godmode_patient, TRAIT_GODMODE, TRAIT_SOURCE_UNIT_TESTS)
	var/mob/living/carbon/human/dying = allocate(/mob/living/carbon/human/consistent)
	damage_chest_to_hardcrit(dying)
	dying.medical_pain.recalculate()
	dying.death()
	TEST_ASSERT(!dying.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown), "Death must clear the hardcrit-health floor.")
	var/mob/living/carbon/human/synthetic = allocate(/mob/living/carbon/human/consistent)
	synthetic.set_species(/datum/species/android)
	damage_chest_to_hardcrit(synthetic)
	synthetic.medical_pain.recalculate()
	TEST_ASSERT(!synthetic.uses_medical_pain(), "Android fixture must opt out of medical pain.")
	var/datum/movespeed_modifier/synthetic_modifier = synthetic.has_movespeed_modifier(/datum/movespeed_modifier/damage_slowdown)
	TEST_ASSERT_NOTNULL(synthetic_modifier, "Synthetic bodies must retain legacy damage impairment.")
	TEST_ASSERT_EQUAL(synthetic_modifier.multiplicative_slowdown, (synthetic.maxHealth - synthetic.health) / MEDICAL_PAIN_DAMAGE_SLOW_DIVISOR, "Synthetic bodies must use the legacy damage formula.")
